/* Auto-generated from p2s.ie — do not edit. */
#ifndef SHAKTI_SHAKTI_P2S_SOURCE_H
#define SHAKTI_SHAKTI_P2S_SOURCE_H
static const char shakti_p2s_source[] =
    "# p2s \20024 strict Python 3 subset to Shakti (not CPython).\n"
    "#\n"
    "# Supported (summary):\n"
    "#   assignment (= \20622 :); chained a = b = e via temp; == \20622 =; chained compare \20622 and;\n"
    "#   def with defaults/kwargs; annotations erased; nested def; @decorator;\n"
    "#   0\200231 arg lambda (no comps in body); if/elif/else, while, for x in; for a, b in \20622 iter temp;\n"
    "#   list/dict comps (one for, optional if) \20622 append / subscript bind;\n"
    "#   lists/tuples/dicts; index/slice; arith // % **; @ \20622 mmul; and/or/not; in;\n"
    "#   bitwise \20622 band/bor/bxor/shl/shr/bnot; += -= *= /=; //= **= %= @= bit-aug\n"
    "#   rewritten to binds; ternary; assert; # comments; one-line f-strings without specs;\n"
    "#   import name; numpy/pandas mapped calls; class with no bases (body flattened).\n"
    "#\n"
    "# Unsupported (hard reject):\n"
    "#   tabs; line joining; inheritance; nested/set/genexp comps; comps in lambda; sets/bytes/complex;\n"
    "#   is; *args/**kwargs; multi-arg lambdas; loop-else; from-import;\n"
    "#   try/with/yield/async; match; del/global/nonlocal; walrus.\n"
    "\n"
    "import converter_shared\n"
    "import transpile_cli\n"
    "\n"
    "python_reserved : [\"def\", \"return\", \"if\", \"elif\", \"else\", \"while\", \"for\", \"in\",\n"
    "                   \"break\", \"continue\", \"and\", \"or\", \"not\", \"import\", \"try\", \"except\",\n"
    "                   \"finally\", \"as\", \"lambda\", \"pass\", \"class\", \"global\", \"del\", \"raise\",\n"
    "                   \"with\", \"yield\", \"True\", \"False\", \"None\"]\n"
    "shakti_reserved : [\"select\", \"update\", \"delete\", \"by\", \"from\", \"where\",\n"
    "                   \"create\", \"insert\", \"into\", \"values\", \"join\", \"on\",\n"
    "                   \"union\", \"outer\"]\n"
    "bit_binop_names : {\"&\":\"band\", \"|\":\"bor\", \"^\":\"bxor\", \"<<\":\"shl\", \">>\":\"shr\"}\n"
    "bit_aug_ops : {\"&=\":\"band\", \"|=\":\"bor\", \"^=\":\"bxor\", \"<<=\":\"shl\", \">>=\":\"shr\"}\n"
    "arith_aug_ops : [\"+=\", \"-=\", \"*=\", \"/=\"]\n"
    "rewrite_aug_ops : [\"//=\", \"**=\", \"%=\", \"@=\", \"&=\", \"|=\", \"^=\", \"<<=\", \">>=\"]\n"
    "\n"
    "def tok(kind, text, val, line, col):\n"
    "    return converter_shared.tok(kind, text, val, line, col)\n"
    "\n"
    "def node(t, x):\n"
    "    return converter_shared.node(t, x)\n"
    "\n"
    "def starts(s, p):\n"
    "    return converter_shared.starts(s, p)\n"
    "\n"
    "def is_alpha(c):\n"
    "    return converter_shared.is_alpha(c)\n"
    "\n"
    "def is_digit(c):\n"
    "    return converter_shared.is_digit(c)\n"
    "\n"
    "def is_alnum(c):\n"
    "    return converter_shared.is_alnum(c)\n"
    "\n"
    "def trim_left(s):\n"
    "    i : 0\n"
    "    while i < len(s) and (s[i] = \" \" or s[i] = \"\\t\"):\n"
    "        i += 1\n"
    "    return s[i:]\n"
    "\n"
    "def quote_string(s):\n"
    "    return converter_shared.quote_string(s)\n"
    "\n"
    "def lex_string(line, i, ln):\n"
    "    start : i\n"
    "    prefix : \"\"\n"
    "    if (line[i] = \"f\" or line[i] = \"F\") and i + 1 < len(line) and (line[i + 1] = \"\\\"\" or line[i + 1] = \"'\"):\n"
    "        prefix : line[i]\n"
    "        i += 1\n"
    "    q : line[i]\n"
    "    triple : False\n"
    "    if i + 2 < len(line) and line[i:i + 3] = q + q + q:\n"
    "        triple : True\n"
    "        i += 3\n"
    "    else:\n"
    "        i += 1\n"
    "    val : \"\"\n"
    "    while i < len(line):\n"
    "        if triple and i + 2 < len(line) and line[i:i + 3] = q + q + q:\n"
    "            i += 3\n"
    "            return [tok(\"STRING\", line[start:i], {\"s\":val, \"f\":prefix != \"\", \"triple\":True}, ln, start + 1), i]\n"
    "        if not triple and line[i] = q:\n"
    "            i += 1\n"
    "            return [tok(\"STRING\", line[start:i], {\"s\":val, \"f\":prefix != \"\", \"triple\":False}, ln, start + 1), i]\n"
    "        if line[i] = \"\\\\\":\n"
    "            if i + 1 >= len(line):\n"
    "                raise str(ln) + \":\" + str(i + 1) + \": unterminated string\"\n"
    "            e : line[i + 1]\n"
    "            if e = \"n\":\n"
    "                val += \"\\n\"\n"
    "            elif e = \"t\":\n"
    "                val += \"\\t\"\n"
    "            elif e = \"r\":\n"
    "                val += \"\\r\"\n"
    "            else:\n"
    "                val += e\n"
    "            i += 2\n"
    "        else:\n"
    "            val += line[i]\n"
    "            i += 1\n"
    "    raise str(ln) + \":\" + str(start + 1) + \": unterminated string\"\n"
    "\n"
    "def lex(source):\n"
    "    lines : re_split(\"\\n\", source)\n"
    "    ts : []\n"
    "    comments : {\"0\":\"\"}\n"
    "    inline : {\"0\":\"\"}\n"
    "    # Keep this heterogeneous: native integer vectors are immutable.\n"
    "    indents : [None, 0]\n"
    "    ln : 1\n"
    "    for line in lines:\n"
    "        nsp : 0\n"
    "        while nsp < len(line) and line[nsp] = \" \":\n"
    "            nsp += 1\n"
    "        if nsp < len(line) and line[nsp] = \"\\t\":\n"
    "            raise str(ln) + \":\" + str(nsp + 1) + \": tabs are unsupported\"\n"
    "        rest : line[nsp:]\n"
    "        if len(rest) = 0:\n"
    "            ln += 1\n"
    "            continue\n"
    "        if rest[0] = \"#\":\n"
    "            comments[str(ln)] : rest\n"
    "            ln += 1\n"
    "            continue\n"
    "        if nsp > indents[len(indents) + -1]:\n"
    "            indents.append(nsp)\n"
    "            ts.append(tok(\"INDENT\", \"\", None, ln, 1))\n"
    "        elif nsp < indents[len(indents) + -1]:\n"
    "            while nsp < indents[len(indents) + -1]:\n"
    "                indents.pop()\n"
    "                ts.append(tok(\"DEDENT\", \"\", None, ln, 1))\n"
    "            if nsp != indents[len(indents) + -1]:\n"
    "                raise str(ln) + \":1: inconsistent indentation\"\n"
    "        i : nsp\n"
    "        while i < len(line):\n"
    "            c : line[i]\n"
    "            if c = \" \" or c = \"\\t\":\n"
    "                i += 1\n"
    "                continue\n"
    "            if c = \"#\":\n"
    "                inline[str(ln)] : line[i:]\n"
    "                break\n"
    "            if is_alpha(c):\n"
    "                if (c = \"f\" or c = \"F\") and i + 1 < len(line) and (line[i + 1] = \"\\\"\" or line[i + 1] = \"'\"):\n"
    "                    z : lex_string(line, i, ln)\n"
    "                    ts.append(z[0])\n"
    "                    i : z[1]\n"
    "                    continue\n"
    "                j : i + 1\n"
    "                while j < len(line) and is_alnum(line[j]):\n"
    "                    j += 1\n"
    "                text : line[i:j]\n"
    "                ts.append(tok(\"NAME\", text, text, ln, i + 1))\n"
    "                i : j\n"
    "                continue\n"
    "            if is_digit(c) or (c = \".\" and i + 1 < len(line) and is_digit(line[i + 1])):\n"
    "                j : i + 1\n"
    "                while j < len(line) and (is_alnum(line[j]) or line[j] = \".\" or line[j] = \"_\"):\n"
    "                    j += 1\n"
    "                if j > i and (line[j + -1] = \"e\" or line[j + -1] = \"E\") and j < len(line) and (line[j] = \"+\" or line[j] = \"-\"):\n"
    "                    if j + 1 < len(line) and is_digit(line[j + 1]):\n"
    "                        j += 1\n"
    "                        while j < len(line) and (is_digit(line[j]) or line[j] = \"_\"):\n"
    "                            j += 1\n"
    "                text : line[i:j]\n"
    "                ts.append(tok(\"NUMBER\", text, text, ln, i + 1))\n"
    "                i : j\n"
    "                continue\n"
    "            if c = \"\\\"\" or c = \"'\":\n"
    "                z : lex_string(line, i, ln)\n"
    "                ts.append(z[0])\n"
    "                i : z[1]\n"
    "                continue\n"
    "            op : c\n"
    "            if i + 2 < len(line) and (line[i:i + 3] = \"**=\" or line[i:i + 3] = \"//=\" or line[i:i + 3] = \"<<=\" or line[i:i + 3] = \">>=\" or line[i:i + 3] = \"...\"):\n"
    "                op : line[i:i + 3]\n"
    "            elif i + 1 < len(line) and line[i:i + 2] in [\"==\", \"!=\", \"<=\", \">=\", \"+=\", \"-=\", \"*=\", \"/=\", \"%=\", \"//\", \"**\", \"<<\", \">>\", \":=\", \"->\", \"@=\", \"&=\", \"|=\", \"^=\"]:\n"
    "                op : line[i:i + 2]\n"
    "            ts.append(tok(\"OP\", op, op, ln, i + 1))\n"
    "            i += len(op)\n"
    "        ts.append(tok(\"NEWLINE\", \"\", None, ln, len(line) + 1))\n"
    "        ln += 1\n"
    "    while len(indents) > 2:\n"
    "        indents.pop()\n"
    "        ts.append(tok(\"DEDENT\", \"\", None, ln, 1))\n"
    "    ts.append(tok(\"ENDMARKER\", \"\", None, ln, 1))\n"
    "    return {\"tokens\":ts, \"comments\":comments, \"inline\":inline}\n"
    "\n"
    "def peek(p):\n"
    "    return converter_shared.peek(p)\n"
    "def peekn(p, n):\n"
    "    return converter_shared.peekn(p, n)\n"
    "def take(p):\n"
    "    return converter_shared.take(p)\n"
    "def at(p, text):\n"
    "    return converter_shared.at(p, text)\n"
    "def kind(p, k):\n"
    "    return converter_shared.kind(p, k)\n"
    "def fail(p, msg, x):\n"
    "    converter_shared.fail(p, msg, x)\n"
    "def need(p, text):\n"
    "    return converter_shared.need(p, text)\n"
    "def need_kind(p, k):\n"
    "    return converter_shared.need_kind(p, k)\n"
    "def ident(p, x):\n"
    "    if x[\"text\"] in python_reserved:\n"
    "        fail(p, \"identifier '\" + x[\"text\"] + \"' is reserved in Shakti\", x)\n"
    "    # Mangle Shakti keywords. Also mangle any name that already starts with\n"
    "    # the mangling prefix so user identifiers like __p2s_values cannot collide\n"
    "    # with a mangled reserved word (values -> __p2s_values).\n"
    "    name : x[\"text\"]\n"
    "    if name in shakti_reserved or starts(name, \"__p2s_\"):\n"
    "        name : \"__p2s_\" + name\n"
    "    x[\"text\"] : name\n"
    "    return name\n"
    "\n"
    "def parse(source, filename):\n"
    "    lx : lex(source)\n"
    "    p : {\"tokens\":lx[\"tokens\"], \"pos\":0, \"filename\":filename, \"aliases\":{\"\":\"\"}, \"comments\":lx[\"comments\"], \"inline\":lx[\"inline\"]}\n"
    "    body : []\n"
    "    while not kind(p, \"ENDMARKER\"):\n"
    "        if kind(p, \"NEWLINE\"):\n"
    "            take(p)\n"
    "        else:\n"
    "            body.append(parse_stmt(p))\n"
    "    return {\"t\":\"Module\", \"body\":body, \"comments\":p[\"comments\"], \"inline\":p[\"inline\"], \"aliases\":p[\"aliases\"], \"filename\":filename}\n"
    "\n"
    "def parse_stmt(p):\n"
    "    decorators : []\n"
    "    while at(p, \"@\"):\n"
    "        take(p)\n"
    "        decorators.append(parse_expr(p))\n"
    "        need_kind(p, \"NEWLINE\")\n"
    "    if len(decorators) > 0:\n"
    "        if not at(p, \"def\"):\n"
    "            fail(p, \"decorators require a function\", peek(p))\n"
    "        x : parse_compound(p)\n"
    "        x[\"decorators\"] : decorators\n"
    "        return x\n"
    "    if at(p, \"if\") or at(p, \"while\") or at(p, \"for\") or at(p, \"def\") or at(p, \"class\") or at(p, \"async\") or at(p, \"with\") or at(p, \"try\"):\n"
    "        return parse_compound(p)\n"
    "    return parse_simple(p)\n"
    "\n"
    "def parse_suite(p):\n"
    "    need(p, \":\")\n"
    "    need_kind(p, \"NEWLINE\")\n"
    "    need_kind(p, \"INDENT\")\n"
    "    xs : []\n"
    "    while not kind(p, \"DEDENT\") and not kind(p, \"ENDMARKER\"):\n"
    "        if kind(p, \"NEWLINE\"):\n"
    "            take(p)\n"
    "        else:\n"
    "            xs.append(parse_stmt(p))\n"
    "    need_kind(p, \"DEDENT\")\n"
    "    if len(xs) = 0:\n"
    "        fail(p, \"empty block\", peek(p))\n"
    "    return xs\n"
    "\n"
    "def parse_class(p):\n"
    "    x : take(p)\n"
    "    name : need_kind(p, \"NAME\")\n"
    "    ident(p, name)\n"
    "    if at(p, \"(\"):\n"
    "        take(p)\n"
    "        if not at(p, \")\"):\n"
    "            fail(p, \"inheritance is unsupported\", peek(p))\n"
    "        need(p, \")\")\n"
    "    body : parse_suite(p)\n"
    "    z : node(\"ClassShell\", x)\n"
    "    z[\"name\"] : name[\"text\"]\n"
    "    z[\"body\"] : body\n"
    "    return z\n"
    "\n"
    "def parse_compound(p):\n"
    "    x : peek(p)\n"
    "    if at(p, \"class\"):\n"
    "        return parse_class(p)\n"
    "    if at(p, \"async\"):\n"
    "        fail(p, \"async functions are unsupported\", x)\n"
    "    if at(p, \"with\"):\n"
    "        fail(p, \"With is unsupported\", x)\n"
    "    if at(p, \"try\"):\n"
    "        fail(p, \"Try is unsupported\", x)\n"
    "    if at(p, \"def\"):\n"
    "        take(p)\n"
    "        name : need_kind(p, \"NAME\")\n"
    "        ident(p, name)\n"
    "        need(p, \"(\")\n"
    "        args : []\n"
    "        defaults : []\n"
    "        if not at(p, \")\"):\n"
    "            while True:\n"
    "                if at(p, \"*\"):\n"
    "                    fail(p, \"variadic or keyword-only parameters are unsupported\", peek(p))\n"
    "                a : need_kind(p, \"NAME\")\n"
    "                ident(p, a)\n"
    "                if at(p, \":\"):\n"
    "                    take(p)\n"
    "                    parse_expr(p)\n"
    "                args.append(a[\"text\"])\n"
    "                if at(p, \"=\"):\n"
    "                    take(p)\n"
    "                    defaults.append(parse_expr(p))\n"
    "                else:\n"
    "                    defaults.append(None)\n"
    "                if not at(p, \",\"):\n"
    "                    break\n"
    "                take(p)\n"
    "                if at(p, \")\"):\n"
    "                    break\n"
    "        need(p, \")\")\n"
    "        if at(p, \"->\"):\n"
    "            take(p)\n"
    "            parse_expr(p)\n"
    "        z : node(\"FunctionDef\", x)\n"
    "        z[\"name\"] : name[\"text\"]\n"
    "        z[\"args\"] : args\n"
    "        z[\"defaults\"] : defaults\n"
    "        z[\"decorators\"] : []\n"
    "        z[\"body\"] : parse_suite(p)\n"
    "        return z\n"
    "    if at(p, \"if\"):\n"
    "        take(p)\n"
    "        z : node(\"If\", x)\n"
    "        z[\"test\"] : parse_expr(p)\n"
    "        z[\"body\"] : parse_suite(p)\n"
    "        z[\"elifs\"] : []\n"
    "        z[\"orelse\"] : []\n"
    "        while at(p, \"elif\"):\n"
    "            e : take(p)\n"
    "            q : {\"test\":parse_expr(p), \"body\":parse_suite(p), \"line\":e[\"line\"], \"col\":e[\"col\"]}\n"
    "            z[\"elifs\"].append(q)\n"
    "        if at(p, \"else\"):\n"
    "            take(p)\n"
    "            z[\"orelse\"] : parse_suite(p)\n"
    "        return z\n"
    "    if at(p, \"while\"):\n"
    "        take(p)\n"
    "        z : node(\"While\", x)\n"
    "        z[\"test\"] : parse_expr(p)\n"
    "        z[\"body\"] : parse_suite(p)\n"
    "        if at(p, \"else\"):\n"
    "            fail(p, \"while-else is unsupported\", peek(p))\n"
    "        return z\n"
    "    if at(p, \"for\"):\n"
    "        take(p)\n"
    "        z : node(\"For\", x)\n"
    "        target : parse_target(p)\n"
    "        if target[\"t\"] = \"Tuple\" or target[\"t\"] = \"List\":\n"
    "            if len(target[\"elts\"]) = 0:\n"
    "                fail(p, \"empty unpacking is unsupported\", target)\n"
    "            for e in target[\"elts\"]:\n"
    "                if e[\"t\"] != \"Name\":\n"
    "                    fail(p, \"nested unpacking is unsupported\", e)\n"
    "        need(p, \"in\")\n"
    "        z[\"target\"] : target\n"
    "        z[\"iter\"] : parse_expr(p)\n"
    "        z[\"body\"] : parse_suite(p)\n"
    "        if at(p, \"else\"):\n"
    "            fail(p, \"for-else is unsupported\", peek(p))\n"
    "        return z\n"
    "    fail(p, \"unsupported compound statement\", x)\n"
    "\n"
    "def end_simple(p):\n"
    "    need_kind(p, \"NEWLINE\")\n"
    "\n"
    "def parse_simple(p):\n"
    "    x : peek(p)\n"
    "    if at(p, \"return\"):\n"
    "        take(p)\n"
    "        z : node(\"Return\", x)\n"
    "        z[\"value\"] : None\n"
    "        if not kind(p, \"NEWLINE\"):\n"
    "            z[\"value\"] : parse_expr(p)\n"
    "        end_simple(p)\n"
    "        return z\n"
    "    if at(p, \"break\") or at(p, \"continue\") or at(p, \"pass\"):\n"
    "        take(p)\n"
    "        z : node(x[\"text\"], x)\n"
    "        end_simple(p)\n"
    "        return z\n"
    "    if at(p, \"from\"):\n"
    "        fail(p, \"from-import is unsupported\", x)\n"
    "    if at(p, \"raise\"):\n"
    "        fail(p, \"Raise is unsupported\", x)\n"
    "    if at(p, \"yield\"):\n"
    "        fail(p, \"Yield is unsupported\", x)\n"
    "    if at(p, \"global\") or at(p, \"nonlocal\") or at(p, \"del\"):\n"
    "        fail(p, x[\"text\"] + \" is unsupported\", x)\n"
    "    if at(p, \"import\"):\n"
    "        take(p)\n"
    "        name : need_kind(p, \"NAME\")\n"
    "        alias : None\n"
    "        if at(p, \"as\"):\n"
    "            take(p)\n"
    "            alias : need_kind(p, \"NAME\")[\"text\"]\n"
    "        if at(p, \",\"):\n"
    "            fail(p, \"multiple imports in one statement are unsupported\", x)\n"
    "        end_simple(p)\n"
    "        z : node(\"Import\", x)\n"
    "        z[\"name\"] : name[\"text\"]\n"
    "        z[\"alias\"] : alias\n"
    "        if name[\"text\"] = \"numpy\" or name[\"text\"] = \"pandas\":\n"
    "            bound : name[\"text\"]\n"
    "            if alias != None:\n"
    "                bound : alias\n"
    "            p[\"aliases\"][bound] : name[\"text\"]\n"
    "            z[\"erase\"] : True\n"
    "        else:\n"
    "            if alias != None:\n"
    "                fail(p, \"import aliases are unsupported\", x)\n"
    "            z[\"erase\"] : False\n"
    "        return z\n"
    "    if at(p, \"assert\"):\n"
    "        take(p)\n"
    "        z : node(\"Assert\", x)\n"
    "        z[\"test\"] : parse_expr(p)\n"
    "        if at(p, \",\"):\n"
    "            fail(p, \"assert message is unsupported\", x)\n"
    "        end_simple(p)\n"
    "        return z\n"
    "    left : parse_expr_list(p)\n"
    "    if at(p, \":\"):\n"
    "        take(p)\n"
    "        parse_expr(p)\n"
    "        if not at(p, \"=\"):\n"
    "            fail(p, \"annotated assignment requires a value\", peek(p))\n"
    "    if at(p, \"=\"):\n"
    "        take(p)\n"
    "        targets : [left]\n"
    "        validate_target(p, left)\n"
    "        while True:\n"
    "            nxt : parse_expr_list(p)\n"
    "            if at(p, \"=\"):\n"
    "                take(p)\n"
    "                validate_target(p, nxt)\n"
    "                targets.append(nxt)\n"
    "            else:\n"
    "                z : node(\"Assign\", x)\n"
    "                z[\"target\"] : targets[0]\n"
    "                z[\"targets\"] : targets\n"
    "                z[\"value\"] : nxt\n"
    "                end_simple(p)\n"
    "                return z\n"
    "    if peek(p)[\"text\"] in arith_aug_ops or peek(p)[\"text\"] in rewrite_aug_ops:\n"
    "        op : take(p)\n"
    "        z : node(\"AugAssign\", x)\n"
    "        z[\"target\"] : left\n"
    "        validate_target(p, left)\n"
    "        z[\"op\"] : op[\"text\"]\n"
    "        z[\"value\"] : parse_expr(p)\n"
    "        end_simple(p)\n"
    "        return z\n"
    "    z : node(\"Expr\", x)\n"
    "    z[\"value\"] : left\n"
    "    end_simple(p)\n"
    "    return z\n"
    "\n"
    "def validate_target(p, x):\n"
    "    if x[\"t\"] = \"Name\" or x[\"t\"] = \"Attr\" or x[\"t\"] = \"Subscript\":\n"
    "        return\n"
    "    if x[\"t\"] = \"Tuple\" or x[\"t\"] = \"List\":\n"
    "        if len(x[\"elts\"]) = 0:\n"
    "            fail(p, \"empty unpacking is unsupported\", x)\n"
    "        for e in x[\"elts\"]:\n"
    "            if e[\"t\"] != \"Name\":\n"
    "                fail(p, \"nested unpacking is unsupported\", e)\n"
    "        return\n"
    "    fail(p, \"unsupported assignment target\", x)\n"
    "\n"
    "def parse_target(p):\n"
    "    first : parse_postfix(p)\n"
    "    if not at(p, \",\"):\n"
    "        return first\n"
    "    z : node(\"Tuple\", first)\n"
    "    z[\"elts\"] : [first]\n"
    "    while at(p, \",\"):\n"
    "        take(p)\n"
    "        z[\"elts\"].append(parse_postfix(p))\n"
    "    return z\n"
    "\n"
    "def parse_expr_list(p):\n"
    "    first : parse_expr(p)\n"
    "    if not at(p, \",\"):\n"
    "        return first\n"
    "    z : node(\"Tuple\", first)\n"
    "    z[\"elts\"] : [first]\n"
    "    while at(p, \",\"):\n"
    "        take(p)\n"
    "        if at(p, \")\") or at(p, \"]\") or kind(p, \"NEWLINE\"):\n"
    "            break\n"
    "        z[\"elts\"].append(parse_expr(p))\n"
    "    return z\n"
    "\n"
    "def parse_expr(p):\n"
    "    if at(p, \"lambda\"):\n"
    "        return parse_lambda(p)\n"
    "    return parse_ifexp(p)\n"
    "\n"
    "def parse_lambda(p):\n"
    "    x : take(p)\n"
    "    args : []\n"
    "    if not at(p, \":\"):\n"
    "        while True:\n"
    "            if at(p, \"*\"):\n"
    "                fail(p, \"variadic or keyword-only lambda parameters are unsupported\", peek(p))\n"
    "            a : need_kind(p, \"NAME\")\n"
    "            args.append(ident(p, a))\n"
    "            if not at(p, \",\"):\n"
    "                break\n"
    "            take(p)\n"
    "    if len(args) > 1:\n"
    "        fail(p, \"multi-argument lambdas are unsupported\", x)\n"
    "    need(p, \":\")\n"
    "    z : node(\"Lambda\", x)\n"
    "    z[\"args\"] : args\n"
    "    z[\"body\"] : parse_expr(p)\n"
    "    return z\n"
    "\n"
    "def parse_ifexp(p):\n"
    "    z : parse_or(p)\n"
    "    if at(p, \"if\"):\n"
    "        x : take(p)\n"
    "        q : node(\"IfExp\", x)\n"
    "        q[\"body\"] : z\n"
    "        q[\"test\"] : parse_or(p)\n"
    "        need(p, \"else\")\n"
    "        q[\"orelse\"] : parse_expr(p)\n"
    "        return q\n"
    "    if at(p, \":=\"):\n"
    "        fail(p, \"walrus operator is unsupported\", peek(p))\n"
    "    return z\n"
    "\n"
    "def parse_or(p):\n"
    "    xs : [parse_and(p)]\n"
    "    x : xs[0]\n"
    "    while at(p, \"or\"):\n"
    "        take(p)\n"
    "        xs.append(parse_and(p))\n"
    "    if len(xs) = 1:\n"
    "        return x\n"
    "    z : node(\"BoolOp\", x)\n"
    "    z[\"op\"] : \"or\"\n"
    "    z[\"values\"] : xs\n"
    "    return z\n"
    "\n"
    "def parse_and(p):\n"
    "    xs : [parse_not(p)]\n"
    "    x : xs[0]\n"
    "    while at(p, \"and\"):\n"
    "        take(p)\n"
    "        xs.append(parse_not(p))\n"
    "    if len(xs) = 1:\n"
    "        return x\n"
    "    z : node(\"BoolOp\", x)\n"
    "    z[\"op\"] : \"and\"\n"
    "    z[\"values\"] : xs\n"
    "    return z\n"
    "\n"
    "def parse_not(p):\n"
    "    if at(p, \"not\") and peekn(p, 1)[\"text\"] != \"in\":\n"
    "        x : take(p)\n"
    "        z : node(\"Unary\", x)\n"
    "        z[\"op\"] : \"not\"\n"
    "        z[\"value\"] : parse_not(p)\n"
    "        return z\n"
    "    return parse_compare(p)\n"
    "\n"
    "def parse_compare(p):\n"
    "    left : parse_bitor(p)\n"
    "    ops : []\n"
    "    vals : []\n"
    "    while peek(p)[\"text\"] in [\"==\", \"!=\", \"<\", \"<=\", \">\", \">=\", \"in\", \"is\"] or (at(p, \"not\") and peekn(p, 1)[\"text\"] = \"in\"):\n"
    "        x : take(p)\n"
    "        op : x[\"text\"]\n"
    "        if op = \"not\":\n"
    "            take(p)\n"
    "            op : \"not in\"\n"
    "        elif op = \"is\":\n"
    "            if at(p, \"not\"):\n"
    "                take(p)\n"
    "            fail(p, \"comparison Is is unsupported\", x)\n"
    "        ops.append(op)\n"
    "        vals.append(parse_bitor(p))\n"
    "    if len(ops) = 0:\n"
    "        return left\n"
    "    if len(ops) = 1:\n"
    "        z : node(\"Compare\", left)\n"
    "        z[\"left\"] : left\n"
    "        z[\"op\"] : ops[0]\n"
    "        z[\"right\"] : vals[0]\n"
    "        return z\n"
    "    cmps : []\n"
    "    prev : left\n"
    "    i : 0\n"
    "    while i < len(ops):\n"
    "        c : node(\"Compare\", prev)\n"
    "        c[\"left\"] : prev\n"
    "        c[\"op\"] : ops[i]\n"
    "        c[\"right\"] : vals[i]\n"
    "        cmps.append(c)\n"
    "        prev : vals[i]\n"
    "        i += 1\n"
    "    z : node(\"BoolOp\", left)\n"
    "    z[\"op\"] : \"and\"\n"
    "    z[\"values\"] : cmps\n"
    "    return z\n"
    "\n"
    "def parse_bitor(p):\n"
    "    return binary(p, parse_bitxor, [\"|\"])\n"
    "\n"
    "def parse_bitxor(p):\n"
    "    return binary(p, parse_bitand, [\"^\"])\n"
    "\n"
    "def parse_bitand(p):\n"
    "    return binary(p, parse_shift, [\"&\"])\n"
    "\n"
    "def parse_shift(p):\n"
    "    return binary(p, parse_arith, [\"<<\", \">>\"])\n"
    "\n"
    "def binary(p, sub, ops):\n"
    "    z : sub(p)\n"
    "    while peek(p)[\"text\"] in ops:\n"
    "        x : take(p)\n"
    "        q : node(\"BinOp\", x)\n"
    "        q[\"left\"] : z\n"
    "        q[\"op\"] : x[\"text\"]\n"
    "        q[\"right\"] : sub(p)\n"
    "        z : q\n"
    "    return z\n"
    "\n"
    "def parse_arith(p):\n"
    "    return binary(p, parse_term, [\"+\", \"-\"])\n"
    "\n"
    "def parse_term(p):\n"
    "    return binary(p, parse_factor, [\"*\", \"/\", \"//\", \"%\", \"@\"])\n"
    "\n"
    "def parse_factor(p):\n"
    "    if peek(p)[\"text\"] in [\"+\", \"-\", \"~\"]:\n"
    "        x : take(p)\n"
    "        if x[\"text\"] = \"+\":\n"
    "            return parse_factor(p)\n"
    "        if x[\"text\"] = \"~\":\n"
    "            z : node(\"Unary\", x)\n"
    "            z[\"op\"] : \"~\"\n"
    "            z[\"value\"] : parse_factor(p)\n"
    "            return z\n"
    "        z : node(\"Unary\", x)\n"
    "        z[\"op\"] : \"-\"\n"
    "        z[\"value\"] : parse_factor(p)\n"
    "        return z\n"
    "    return parse_power(p)\n"
    "\n"
    "def parse_power(p):\n"
    "    z : parse_postfix(p)\n"
    "    if at(p, \"**\"):\n"
    "        x : take(p)\n"
    "        q : node(\"BinOp\", x)\n"
    "        q[\"left\"] : z\n"
    "        q[\"op\"] : \"**\"\n"
    "        q[\"right\"] : parse_factor(p)\n"
    "        return q\n"
    "    return z\n"
    "\n"
    "def parse_postfix(p):\n"
    "    z : parse_atom(p)\n"
    "    while True:\n"
    "        if at(p, \".\"):\n"
    "            x : take(p)\n"
    "            a : need_kind(p, \"NAME\")\n"
    "            q : node(\"Attr\", x)\n"
    "            q[\"value\"] : z\n"
    "            q[\"attr\"] : a[\"text\"]\n"
    "            z : q\n"
    "        elif at(p, \"(\"):\n"
    "            x : take(p)\n"
    "            q : node(\"Call\", x)\n"
    "            q[\"func\"] : z\n"
    "            q[\"args\"] : []\n"
    "            q[\"kwargs\"] : []\n"
    "            if not at(p, \")\"):\n"
    "                while True:\n"
    "                    if at(p, \"**\"):\n"
    "                        fail(p, \"**kwargs is unsupported\", peek(p))\n"
    "                    if at(p, \"*\"):\n"
    "                        fail(p, \"*args is unsupported\", peek(p))\n"
    "                    if kind(p, \"NAME\") and peekn(p, 1)[\"text\"] = \"=\":\n"
    "                        k : take(p)\n"
    "                        ident(p, k)\n"
    "                        take(p)\n"
    "                        q[\"kwargs\"].append([k, parse_expr(p)])\n"
    "                    else:\n"
    "                        q[\"args\"].append(parse_expr(p))\n"
    "                    if not at(p, \",\"):\n"
    "                        break\n"
    "                    take(p)\n"
    "                    if at(p, \")\"):\n"
    "                        break\n"
    "            need(p, \")\")\n"
    "            z : q\n"
    "        elif at(p, \"[\"):\n"
    "            x : take(p)\n"
    "            q : node(\"Subscript\", x)\n"
    "            q[\"value\"] : z\n"
    "            q[\"slice\"] : parse_slice_list(p)\n"
    "            need(p, \"]\")\n"
    "            z : q\n"
    "        else:\n"
    "            break\n"
    "    return z\n"
    "\n"
    "def parse_slice_list(p):\n"
    "    xs : [parse_slice(p)]\n"
    "    while at(p, \",\"):\n"
    "        take(p)\n"
    "        xs.append(parse_slice(p))\n"
    "    if len(xs) = 1:\n"
    "        return xs[0]\n"
    "    z : node(\"SliceTuple\", xs[0])\n"
    "    z[\"elts\"] : xs\n"
    "    return z\n"
    "\n"
    "def parse_slice(p):\n"
    "    x : peek(p)\n"
    "    lower : None\n"
    "    if not at(p, \":\"):\n"
    "        lower : parse_expr(p)\n"
    "    if not at(p, \":\"):\n"
    "        return lower\n"
    "    take(p)\n"
    "    upper : None\n"
    "    step : None\n"
    "    if not at(p, \":\") and not at(p, \"]\") and not at(p, \",\"):\n"
    "        upper : parse_expr(p)\n"
    "    if at(p, \":\"):\n"
    "        take(p)\n"
    "        if not at(p, \"]\") and not at(p, \",\"):\n"
    "            step : parse_expr(p)\n"
    "    z : node(\"Slice\", x)\n"
    "    z[\"lower\"] : lower\n"
    "    z[\"upper\"] : upper\n"
    "    z[\"step\"] : step\n"
    "    return z\n"
    "\n"
    "def parse_atom(p):\n"
    "    x : peek(p)\n"
    "    if kind(p, \"NUMBER\"):\n"
    "        take(p)\n"
    "        if \"j\" in x[\"text\"] or \"J\" in x[\"text\"]:\n"
    "            fail(p, \"complex literals are unsupported\", x)\n"
    "        z : node(\"Const\", x)\n"
    "        z[\"value\"] : x[\"text\"]\n"
    "        z[\"kind\"] : \"number\"\n"
    "        return z\n"
    "    if kind(p, \"STRING\"):\n"
    "        take(p)\n"
    "        if x[\"val\"][\"f\"]:\n"
    "            depth : 0\n"
    "            j : 0\n"
    "            while j < len(x[\"val\"][\"s\"]):\n"
    "                c : x[\"val\"][\"s\"][j]\n"
    "                if c = \"{\":\n"
    "                    if j + 1 < len(x[\"val\"][\"s\"]) and x[\"val\"][\"s\"][j + 1] = \"{\":\n"
    "                        j += 2\n"
    "                        continue\n"
    "                    depth += 1\n"
    "                elif c = \"}\":\n"
    "                    depth += -1\n"
    "                elif depth > 0 and (c = \"!\" or c = \":\"):\n"
    "                    fail(p, \"f-string conversions/format specs are unsupported\", x)\n"
    "                j += 1\n"
    "        z : node(\"FString\" if x[\"val\"][\"f\"] else \"Const\", x)\n"
    "        z[\"value\"] : x[\"val\"][\"s\"]\n"
    "        z[\"kind\"] : \"string\"\n"
    "        return z\n"
    "    if kind(p, \"NAME\"):\n"
    "        take(p)\n"
    "        if (x[\"text\"] = \"b\" or x[\"text\"] = \"B\") and kind(p, \"STRING\"):\n"
    "            fail(p, \"bytes literals are unsupported\", x)\n"
    "        if x[\"text\"] = \"await\":\n"
    "            fail(p, \"Await is unsupported\", x)\n"
    "        if x[\"text\"] = \"yield\":\n"
    "            fail(p, \"Yield is unsupported\", x)\n"
    "        z : node(\"Const\" if x[\"text\"] in [\"True\", \"False\", \"None\"] else \"Name\", x)\n"
    "        z[\"value\"] : x[\"text\"] if z[\"t\"] = \"Const\" else ident(p, x)\n"
    "        if z[\"t\"] = \"Name\":\n"
    "            x[\"text\"] : z[\"value\"]\n"
    "        return z\n"
    "    if at(p, \"(\"):\n"
    "        take(p)\n"
    "        if at(p, \")\"):\n"
    "            take(p)\n"
    "            z : node(\"Tuple\", x)\n"
    "            z[\"elts\"] : []\n"
    "            return z\n"
    "        z : parse_expr_list(p)\n"
    "        if at(p, \"for\"):\n"
    "            fail(p, \"comprehensions are unsupported\", peek(p))\n"
    "        need(p, \")\")\n"
    "        return z\n"
    "    if at(p, \"[\"):\n"
    "        take(p)\n"
    "        z : node(\"List\", x)\n"
    "        z[\"elts\"] : []\n"
    "        if not at(p, \"]\"):\n"
    "            e : parse_expr(p)\n"
    "            if at(p, \"for\"):\n"
    "                return parse_comp_tail(p, x, \"ListComp\", e, None)\n"
    "            z[\"elts\"].append(e)\n"
    "            while at(p, \",\"):\n"
    "                take(p)\n"
    "                if at(p, \"]\"):\n"
    "                    break\n"
    "                e : parse_expr(p)\n"
    "                if at(p, \"for\"):\n"
    "                    fail(p, \"comprehensions are unsupported\", x)\n"
    "                z[\"elts\"].append(e)\n"
    "        need(p, \"]\")\n"
    "        return z\n"
    "    if at(p, \"{\"):\n"
    "        take(p)\n"
    "        z : node(\"Dict\", x)\n"
    "        z[\"keys\"] : []\n"
    "        z[\"values\"] : []\n"
    "        if not at(p, \"}\"):\n"
    "            if at(p, \"**\"):\n"
    "                fail(p, \"dict unpacking is unsupported\", peek(p))\n"
    "            k : parse_expr(p)\n"
    "            if at(p, \"for\"):\n"
    "                fail(p, \"set comprehensions are unsupported\", x)\n"
    "            if not at(p, \":\"):\n"
    "                fail(p, \"set literals are unsupported\", x)\n"
    "            need(p, \":\")\n"
    "            v : parse_expr(p)\n"
    "            if at(p, \"for\"):\n"
    "                return parse_comp_tail(p, x, \"DictComp\", k, v)\n"
    "            z[\"keys\"].append(k)\n"
    "            z[\"values\"].append(v)\n"
    "            while at(p, \",\"):\n"
    "                take(p)\n"
    "                if at(p, \"}\"):\n"
    "                    break\n"
    "                if at(p, \"**\"):\n"
    "                    fail(p, \"dict unpacking is unsupported\", peek(p))\n"
    "                k : parse_expr(p)\n"
    "                if at(p, \"for\"):\n"
    "                    fail(p, \"comprehensions are unsupported\", x)\n"
    "                if not at(p, \":\"):\n"
    "                    fail(p, \"set literals are unsupported\", x)\n"
    "                need(p, \":\")\n"
    "                z[\"keys\"].append(k)\n"
    "                z[\"values\"].append(parse_expr(p))\n"
    "        need(p, \"}\")\n"
    "        return z\n"
    "    fail(p, \"unsupported expression\", x)\n"
    "\n"
    "def parse_comp_tail(p, x, kind, elt, val):\n"
    "    take(p)\n"
    "    target : parse_target(p)\n"
    "    if target[\"t\"] = \"Tuple\" or target[\"t\"] = \"List\":\n"
    "        if len(target[\"elts\"]) = 0:\n"
    "            fail(p, \"empty unpacking is unsupported\", target)\n"
    "        for e in target[\"elts\"]:\n"
    "            if e[\"t\"] != \"Name\":\n"
    "                fail(p, \"nested unpacking is unsupported\", e)\n"
    "    need(p, \"in\")\n"
    "    it : parse_or(p)\n"
    "    if at(p, \"for\"):\n"
    "        fail(p, \"nested comprehensions are unsupported\", peek(p))\n"
    "    filt : None\n"
    "    if at(p, \"if\"):\n"
    "        take(p)\n"
    "        filt : parse_expr(p)\n"
    "        if at(p, \"for\"):\n"
    "            fail(p, \"nested comprehensions are unsupported\", peek(p))\n"
    "    if kind = \"ListComp\":\n"
    "        need(p, \"]\")\n"
    "    else:\n"
    "        need(p, \"}\")\n"
    "    z : node(kind, x)\n"
    "    z[\"elt\"] : elt\n"
    "    z[\"value\"] : val\n"
    "    z[\"target\"] : target\n"
    "    z[\"iter\"] : it\n"
    "    z[\"filt\"] : filt\n"
    "    return z\n"
    "\n"
    "def pad(n):\n"
    "    return converter_shared.pad(n)\n"
    "\n"
    "def contains_comp(x):\n"
    "    if x = None:\n"
    "        return False\n"
    "    tx : type(x)\n"
    "    if tx = \"list\":\n"
    "        for e in x:\n"
    "            if contains_comp(e):\n"
    "                return True\n"
    "        return False\n"
    "    if tx != \"dict\":\n"
    "        return False\n"
    "    if \"t\" in x:\n"
    "        if x[\"t\"] = \"ListComp\" or x[\"t\"] = \"DictComp\":\n"
    "            return True\n"
    "    for k in x.keys():\n"
    "        if contains_comp(x[k]):\n"
    "            return True\n"
    "    return False\n"
    "\n"
    "def comp_fail(st, x, msg):\n"
    "    raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": \" + msg\n"
    "\n"
    "def gensym(st, prefix):\n"
    "    if not \"tmpn\" in st:\n"
    "        st[\"tmpn\"] : 0\n"
    "    st[\"tmpn\"] += 1\n"
    "    return \"__p2s_\" + prefix + str(st[\"tmpn\"])\n"
    "\n"
    "def push_pre(st, line):\n"
    "    if not \"pre\" in st:\n"
    "        st[\"pre\"] : []\n"
    "    st[\"pre\"].append(line)\n"
    "\n"
    "def flush_pre(st, ind):\n"
    "    out : []\n"
    "    if not \"pre\" in st:\n"
    "        return out\n"
    "    for line in st[\"pre\"]:\n"
    "        out.append(pad(ind) + line)\n"
    "    st[\"pre\"] : []\n"
    "    return out\n"
    "\n"
    "def emit_comp(st, x, is_list):\n"
    "    nested : contains_comp(x[\"elt\"]) or contains_comp(x[\"iter\"])\n"
    "    if x[\"filt\"] != None and contains_comp(x[\"filt\"]):\n"
    "        nested : True\n"
    "    if x[\"value\"] != None and contains_comp(x[\"value\"]):\n"
    "        nested : True\n"
    "    if nested:\n"
    "        comp_fail(st, x, \"nested comprehensions are unsupported\")\n"
    "    tmp : gensym(st, \"c\")\n"
    "    if is_list:\n"
    "        push_pre(st, tmp + \" : []\")\n"
    "    else:\n"
    "        push_pre(st, tmp + \" : {}\")\n"
    "    it : expr_text(x[\"iter\"], st)\n"
    "    tgt : x[\"target\"]\n"
    "    body : \"    \"\n"
    "    if tgt[\"t\"] = \"Tuple\" or tgt[\"t\"] = \"List\":\n"
    "        itv : gensym(st, \"it\")\n"
    "        push_pre(st, \"for \" + itv + \" in \" + it + \":\")\n"
    "        push_pre(st, \"    \" + target_text(tgt, st) + \" : \" + itv)\n"
    "        body : \"    \"\n"
    "    else:\n"
    "        push_pre(st, \"for \" + target_text(tgt, st) + \" in \" + it + \":\")\n"
    "    if x[\"filt\"] != None:\n"
    "        push_pre(st, body + \"if \" + expr_text(x[\"filt\"], st) + \":\")\n"
    "        body += \"    \"\n"
    "    if is_list:\n"
    "        push_pre(st, body + tmp + \".append(\" + expr_text(x[\"elt\"], st) + \")\")\n"
    "    else:\n"
    "        push_pre(st, body + tmp + \"[\" + expr_text(x[\"elt\"], st) + \"] : \" + expr_text(x[\"value\"], st))\n"
    "    return tmp\n"
    "\n"
    "def render(ast, state):\n"
    "    state[\"comments\"] : ast[\"comments\"]\n"
    "    state[\"inline\"] : ast[\"inline\"]\n"
    "    state[\"last_comment\"] : 0\n"
    "    state[\"filename\"] : ast[\"filename\"]\n"
    "    if not \"pre\" in state:\n"
    "        state[\"pre\"] : []\n"
    "    if not \"tmpn\" in state:\n"
    "        state[\"tmpn\"] : 0\n"
    "    lines : render_body(ast[\"body\"], state, 0, True)\n"
    "    for k in state[\"comments\"].keys():\n"
    "        kn : int(k)\n"
    "        if kn > state[\"last_comment\"]:\n"
    "            lines.append(state[\"comments\"][k])\n"
    "    text : \"\"\n"
    "    for line in lines:\n"
    "        if line != \"\":\n"
    "            text += line + \"\\n\"\n"
    "    return text\n"
    "\n"
    "def before_comments(st, line, indent):\n"
    "    out : []\n"
    "    for k in st[\"comments\"].keys():\n"
    "        kn : int(k)\n"
    "        if kn > st[\"last_comment\"] and kn < line:\n"
    "            out.append(pad(indent) + st[\"comments\"][k])\n"
    "            st[\"last_comment\"] : kn\n"
    "    return out\n"
    "\n"
    "def render_body(body, st, indent, doc_ok):\n"
    "    out : []\n"
    "    i : 0\n"
    "    while i < len(body):\n"
    "        s : body[i]\n"
    "        cs : before_comments(st, s[\"line\"], indent)\n"
    "        for c in cs:\n"
    "            out.append(c)\n"
    "        if doc_ok and i = 0 and s[\"t\"] = \"Expr\" and s[\"value\"][\"t\"] = \"Const\" and s[\"value\"][\"kind\"] = \"string\":\n"
    "            parts : re_split(\"\\n\", s[\"value\"][\"value\"])\n"
    "            for q in parts:\n"
    "                out.append(pad(indent) + (\"# \" + q if len(q) > 0 else \"#\"))\n"
    "        else:\n"
    "            rs : render_stmt(s, st, indent)\n"
    "            key : str(s[\"line\"])\n"
    "            if key in st[\"inline\"] and len(rs) > 0:\n"
    "                last : len(rs) + -1\n"
    "                rs[last] : rs[last] + \"  \" + st[\"inline\"][key]\n"
    "            for q in rs:\n"
    "                if q != \"\":\n"
    "                    out.append(q)\n"
    "        i += 1\n"
    "    return out\n"
    "\n"
    "def render_stmt(s, st, ind):\n"
    "    p : pad(ind)\n"
    "    t : s[\"t\"]\n"
    "    if t = \"Assign\":\n"
    "        val : expr_text(s[\"value\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        ts : s[\"targets\"] if \"targets\" in s else [s[\"target\"]]\n"
    "        if len(ts) = 1:\n"
    "            out.append(p + target_text(ts[0], st) + \" : \" + val)\n"
    "            return out\n"
    "        tmp : gensym(st, \"t\")\n"
    "        out.append(p + tmp + \" : \" + val)\n"
    "        i : len(ts) + -1\n"
    "        while i >= 0:\n"
    "            out.append(p + target_text(ts[i], st) + \" : \" + tmp)\n"
    "            i += -1\n"
    "        return out\n"
    "    if t = \"AugAssign\":\n"
    "        tgt : target_text(s[\"target\"], st)\n"
    "        val : expr_text(s[\"value\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        if s[\"op\"] in arith_aug_ops:\n"
    "            out.append(p + tgt + \" \" + s[\"op\"] + \" \" + val)\n"
    "            return out\n"
    "        if s[\"op\"] = \"@=\":\n"
    "            rhs : \"mmul(\" + tgt + \", \" + val + \")\"\n"
    "        elif s[\"op\"] in bit_aug_ops:\n"
    "            rhs : bit_aug_ops[s[\"op\"]] + \"(\" + tgt + \", \" + val + \")\"\n"
    "        else:\n"
    "            binop : s[\"op\"][0:len(s[\"op\"]) + -1]\n"
    "            rhs : \"(\" + tgt + \" \" + binop + \" \" + val + \")\"\n"
    "        out.append(p + tgt + \" : \" + rhs)\n"
    "        return out\n"
    "    if t = \"Return\":\n"
    "        if s[\"value\"] = None:\n"
    "            return [p + \"return\"]\n"
    "        val : expr_text(s[\"value\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        out.append(p + \"return \" + val)\n"
    "        return out\n"
    "    if t = \"pass\" or t = \"break\" or t = \"continue\":\n"
    "        return [p + t]\n"
    "    if t = \"ClassShell\":\n"
    "        out : []\n"
    "        for c in s[\"body\"]:\n"
    "            for q in render_stmt(c, st, ind):\n"
    "                out.append(q)\n"
    "        if len(out) = 0:\n"
    "            return [p + \"pass\"]\n"
    "        return out\n"
    "    if t = \"Import\":\n"
    "        return [\"\" if s[\"erase\"] else p + \"import \" + s[\"name\"]]\n"
    "    if t = \"Assert\":\n"
    "        val : expr_text(s[\"test\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        out.append(p + \"assert(\" + val + \")\")\n"
    "        return out\n"
    "    if t = \"Expr\":\n"
    "        val : expr_text(s[\"value\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        out.append(p + val)\n"
    "        return out\n"
    "    if t = \"FunctionDef\":\n"
    "        out : []\n"
    "        deco_txt : []\n"
    "        for d in s[\"decorators\"]:\n"
    "            deco_txt.append(expr_text(d, st))\n"
    "        parts : []\n"
    "        i : 0\n"
    "        while i < len(s[\"args\"]):\n"
    "            q : s[\"args\"][i]\n"
    "            if s[\"defaults\"][i] != None:\n"
    "                q += \":\" + expr_text(s[\"defaults\"][i], st)\n"
    "            parts.append(q)\n"
    "            i += 1\n"
    "        pre : flush_pre(st, ind)\n"
    "        for q in pre:\n"
    "            out.append(q)\n"
    "        for d in deco_txt:\n"
    "            out.append(p + \"@\" + d)\n"
    "        out.append(p + \"def \" + s[\"name\"] + \"(\" + join_text(parts, \", \") + \"):\")\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, True):\n"
    "            out.append(q)\n"
    "        return out\n"
    "    if t = \"If\":\n"
    "        test : expr_text(s[\"test\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        out.append(p + \"if \" + test + \":\")\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "            out.append(q)\n"
    "        for e in s[\"elifs\"]:\n"
    "            et : expr_text(e[\"test\"], st)\n"
    "            for q in flush_pre(st, ind):\n"
    "                out.append(q)\n"
    "            out.append(p + \"elif \" + et + \":\")\n"
    "            for q in render_body(e[\"body\"], st, ind + 1, False):\n"
    "                out.append(q)\n"
    "        if len(s[\"orelse\"]) > 0:\n"
    "            out.append(p + \"else:\")\n"
    "            for q in render_body(s[\"orelse\"], st, ind + 1, False):\n"
    "                out.append(q)\n"
    "        return out\n"
    "    if t = \"While\":\n"
    "        test : expr_text(s[\"test\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        out.append(p + \"while \" + test + \":\")\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "            out.append(q)\n"
    "        return out\n"
    "    if t = \"For\":\n"
    "        it : expr_text(s[\"iter\"], st)\n"
    "        out : flush_pre(st, ind)\n"
    "        tgt : s[\"target\"]\n"
    "        if tgt[\"t\"] = \"Tuple\" or tgt[\"t\"] = \"List\":\n"
    "            tmp : gensym(st, \"it\")\n"
    "            out.append(p + \"for \" + tmp + \" in \" + it + \":\")\n"
    "            out.append(pad(ind + 1) + target_text(tgt, st) + \" : \" + tmp)\n"
    "            for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "                out.append(q)\n"
    "            return out\n"
    "        out.append(p + \"for \" + target_text(tgt, st) + \" in \" + it + \":\")\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "            out.append(q)\n"
    "        return out\n"
    "    return []\n"
    "\n"
    "def join_text(xs, sep):\n"
    "    return converter_shared.join_text(xs, sep)\n"
    "def target_text(x, st):\n"
    "    if x[\"t\"] = \"Tuple\" or x[\"t\"] = \"List\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(target_text(e, st))\n"
    "        return join_text(parts, \", \")\n"
    "    return expr_text(x, st)\n"
    "\n"
    "def slice_text(x, st):\n"
    "    if x[\"t\"] = \"Slice\":\n"
    "        a : \"\" if x[\"lower\"] = None else expr_text(x[\"lower\"], st)\n"
    "        b : \"\" if x[\"upper\"] = None else expr_text(x[\"upper\"], st)\n"
    "        q : a + \":\" + b\n"
    "        if x[\"step\"] != None:\n"
    "            q += \":\" + expr_text(x[\"step\"], st)\n"
    "        return q\n"
    "    if x[\"t\"] = \"SliceTuple\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(slice_text(e, st))\n"
    "        return join_text(parts, \", \")\n"
    "    return expr_text(x, st)\n"
    "\n"
    "def expr_text(x, st):\n"
    "    t : x[\"t\"]\n"
    "    if t = \"Name\":\n"
    "        return x[\"value\"]\n"
    "    if t = \"Const\":\n"
    "        if \"kind\" in x and x[\"kind\"] = \"string\":\n"
    "            return quote_string(x[\"value\"])\n"
    "        if \"kind\" in x and x[\"kind\"] = \"number\":\n"
    "            return converter_shared.num_clean(x[\"value\"])\n"
    "        return x[\"value\"]\n"
    "    if t = \"FString\":\n"
    "        return \"f\" + quote_string(x[\"value\"])\n"
    "    if t = \"List\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return \"[\" + join_text(parts, \", \") + \"]\"\n"
    "    if t = \"Tuple\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        if len(parts) = 1:\n"
    "            return \"(\" + parts[0] + \",)\"\n"
    "        return \"(\" + join_text(parts, \", \") + \")\"\n"
    "    if t = \"Dict\":\n"
    "        parts : []\n"
    "        i : 0\n"
    "        while i < len(x[\"keys\"]):\n"
    "            parts.append(expr_text(x[\"keys\"][i], st) + \": \" + expr_text(x[\"values\"][i], st))\n"
    "            i += 1\n"
    "        return \"{\" + join_text(parts, \", \") + \"}\"\n"
    "    if t = \"Attr\":\n"
    "        if x[\"value\"][\"t\"] = \"Name\" and x[\"value\"][\"value\"] in st[\"aliases\"]:\n"
    "            raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": \" + st[\"aliases\"][x[\"value\"][\"value\"]] + \".\" + x[\"attr\"] + \" is unsupported outside a mapped call\"\n"
    "        return expr_text(x[\"value\"], st) + \".\" + x[\"attr\"]\n"
    "    if t = \"Subscript\":\n"
    "        return expr_text(x[\"value\"], st) + \"[\" + slice_text(x[\"slice\"], st) + \"]\"\n"
    "    if t = \"Unary\":\n"
    "        if x[\"op\"] = \"not\":\n"
    "            return \"(not \" + expr_text(x[\"value\"], st) + \")\"\n"
    "        if x[\"op\"] = \"~\":\n"
    "            return \"bnot(\" + expr_text(x[\"value\"], st) + \")\"\n"
    "        return \"(-\" + expr_text(x[\"value\"], st) + \")\"\n"
    "    if t = \"BinOp\":\n"
    "        if x[\"op\"] = \"@\":\n"
    "            return \"mmul(\" + expr_text(x[\"left\"], st) + \", \" + expr_text(x[\"right\"], st) + \")\"\n"
    "        if x[\"op\"] in bit_binop_names:\n"
    "            return bit_binop_names[x[\"op\"]] + \"(\" + expr_text(x[\"left\"], st) + \", \" + expr_text(x[\"right\"], st) + \")\"\n"
    "        return \"(\" + expr_text(x[\"left\"], st) + \" \" + x[\"op\"] + \" \" + expr_text(x[\"right\"], st) + \")\"\n"
    "    if t = \"BoolOp\":\n"
    "        parts : []\n"
    "        for e in x[\"values\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return \"(\" + join_text(parts, \" \" + x[\"op\"] + \" \") + \")\"\n"
    "    if t = \"Compare\":\n"
    "        op : \"=\" if x[\"op\"] = \"==\" else x[\"op\"]\n"
    "        return \"(\" + expr_text(x[\"left\"], st) + \" \" + op + \" \" + expr_text(x[\"right\"], st) + \")\"\n"
    "    if t = \"IfExp\":\n"
    "        return expr_text(x[\"body\"], st) + \" if \" + expr_text(x[\"test\"], st) + \" else \" + expr_text(x[\"orelse\"], st)\n"
    "    if t = \"Lambda\":\n"
    "        if contains_comp(x[\"body\"]):\n"
    "            comp_fail(st, x, \"comprehensions in lambda are unsupported\")\n"
    "        return \"(lambda \" + join_text(x[\"args\"], \", \") + \": \" + expr_text(x[\"body\"], st) + \")\"\n"
    "    if t = \"Call\":\n"
    "        lowered : lower_call(x, st)\n"
    "        if lowered != None:\n"
    "            return lowered\n"
    "        parts : []\n"
    "        for e in x[\"args\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        for kv in x[\"kwargs\"]:\n"
    "            parts.append(kv[0][\"text\"] + \":\" + expr_text(kv[1], st))\n"
    "        return expr_text(x[\"func\"], st) + \"(\" + join_text(parts, \", \") + \")\"\n"
    "    if t = \"ListComp\":\n"
    "        return emit_comp(st, x, True)\n"
    "    if t = \"DictComp\":\n"
    "        return emit_comp(st, x, False)\n"
    "    return \"\"\n"
    "\n"
    "def lower_call(x, st):\n"
    "    f : x[\"func\"]\n"
    "    if f[\"t\"] != \"Attr\" or f[\"value\"][\"t\"] != \"Name\":\n"
    "        return None\n"
    "    alias : f[\"value\"][\"value\"]\n"
    "    if not alias in st[\"aliases\"]:\n"
    "        return None\n"
    "    mod : st[\"aliases\"][alias]\n"
    "    name : f[\"attr\"]\n"
    "    if mod = \"numpy\":\n"
    "        if name = \"array\" or name = \"asarray\":\n"
    "            if len(x[\"args\"]) != 1 or len(x[\"kwargs\"]) != 0:\n"
    "                raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": numpy.\" + name + \" requires one argument without dtype/options\"\n"
    "            return expr_text(x[\"args\"][0], st)\n"
    "        maps : {\"sum\":\"sum\", \"mean\":\"avg\", \"min\":\"min\", \"max\":\"max\", \"dot\":\"dot\",\n"
    "                \"matmul\":\"mmul\", \"abs\":\"abs\", \"sqrt\":\"sqrt\", \"exp\":\"exp\", \"log\":\"log\",\n"
    "                \"sin\":\"sin\", \"cos\":\"cos\", \"tan\":\"tan\"}\n"
    "        if not name in maps:\n"
    "            raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": numpy.\" + name + \" is unsupported\"\n"
    "        if len(x[\"kwargs\"]) > 0:\n"
    "            raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": numpy.\" + name + \" options are unsupported\"\n"
    "        parts : []\n"
    "        for e in x[\"args\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return maps[name] + \"(\" + join_text(parts, \", \") + \")\"\n"
    "    if mod = \"pandas\":\n"
    "        if name = \"Series\":\n"
    "            if len(x[\"args\"]) != 1 or len(x[\"kwargs\"]) != 0:\n"
    "                raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": pandas.Series requires one argument\"\n"
    "            return expr_text(x[\"args\"][0], st)\n"
    "        if name != \"DataFrame\":\n"
    "            raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": pandas.\" + name + \" is unsupported\"\n"
    "        if len(x[\"args\"]) != 1 or len(x[\"kwargs\"]) != 0 or x[\"args\"][0][\"t\"] != \"Dict\":\n"
    "            raise st[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": pandas.DataFrame requires one dictionary argument\"\n"
    "        d : x[\"args\"][0]\n"
    "        parts : []\n"
    "        i : 0\n"
    "        while i < len(d[\"keys\"]):\n"
    "            k : d[\"keys\"][i]\n"
    "            if k[\"t\"] != \"Const\" or k[\"kind\"] != \"string\" or not re_match(\"^[A-Za-z_][A-Za-z0-9_]*$\", k[\"value\"]):\n"
    "                raise st[\"filename\"] + \":\" + str(k[\"line\"]) + \":\" + str(k[\"col\"]) + \": DataFrame column names must be valid string identifiers\"\n"
    "            parts.append(k[\"value\"] + \":\" + expr_text(d[\"values\"][i], st))\n"
    "            i += 1\n"
    "        return \"table(\" + join_text(parts, \", \") + \")\"\n"
    "    return None\n"
    "\n"
    "def transpile(source, filename):\n"
    "    ast : parse(source, filename)\n"
    "    return render(ast, {\"aliases\":ast[\"aliases\"], \"pre\":[], \"tmpn\":0})\n"
    "\n"
    "def main():\n"
    "    return transpile_cli.run(argv, \"p2s.ie\", \"py\", transpile)\n"
    "\n"
    "# Run CLI only when this file is the entry script.\n"
    "if re_match(\"p2s\\\\.ie$\", argv[0]):\n"
    "    main()\n"
;
#endif /* SHAKTI_SHAKTI_P2S_SOURCE_H */
