/* Auto-generated from c2s.ie — do not edit. */
#ifndef SHAKTI_SHAKTI_C2S_SOURCE_H
#define SHAKTI_SHAKTI_C2S_SOURCE_H
static const char shakti_c2s_source[] =
    "# c2s -- strict C subset to Shakti.\n"
    "\n"
    "shakti_reserved : [\"select\", \"update\", \"delete\", \"by\", \"from\", \"where\",\n"
    "                   \"create\", \"insert\", \"into\", \"values\", \"join\", \"on\"]\n"
    "c_keywords : [\"if\", \"else\", \"while\", \"for\", \"do\", \"switch\", \"case\", \"default\",\n"
    "              \"return\", \"break\", \"continue\", \"goto\", \"typedef\", \"struct\",\n"
    "              \"union\", \"enum\", \"sizeof\", \"static\", \"extern\", \"register\",\n"
    "              \"auto\", \"volatile\", \"restrict\", \"inline\", \"const\", \"signed\",\n"
    "              \"unsigned\", \"void\", \"int\", \"long\", \"short\", \"double\", \"float\",\n"
    "              \"char\", \"bool\", \"_Bool\", \"true\", \"false\", \"NULL\"]\n"
    "c_type_keywords : [\"void\", \"int\", \"long\", \"short\", \"double\", \"float\", \"char\",\n"
    "                   \"bool\", \"_Bool\", \"size_t\"]\n"
    "c_type_modifiers : [\"const\", \"unsigned\", \"signed\", \"short\", \"long\"]\n"
    "c_forbidden_names : [\"malloc\", \"free\", \"sizeof\"]\n"
    "two_ops : [\"==\", \"!=\", \"<=\", \">=\", \"&&\", \"||\", \"++\", \"--\", \"+=\", \"-=\", \"*=\",\n"
    "           \"/=\", \"->\", \"<<\", \">>\"]\n"
    "\n"
    "def is_kw(text):\n"
    "    return text in c_keywords\n"
    "\n"
    "def is_type_kw(text):\n"
    "    return text in c_type_keywords\n"
    "\n"
    "def is_type_mod(text):\n"
    "    return text in c_type_modifiers\n"
    "\n"
    "def tok(kind, text, val, line, col):\n"
    "    return {\"kind\":kind, \"text\":text, \"val\":val, \"line\":line, \"col\":col}\n"
    "\n"
    "def node(t, x):\n"
    "    return {\"t\":t, \"line\":x[\"line\"], \"col\":x[\"col\"]}\n"
    "\n"
    "def starts(s, p):\n"
    "    if len(s) < len(p):\n"
    "        return False\n"
    "    return s[0:len(p)] = p\n"
    "\n"
    "def is_alpha(c):\n"
    "    return (\"a\" <= c and c <= \"z\") or (\"A\" <= c and c <= \"Z\") or c = \"_\"\n"
    "\n"
    "def is_digit(c):\n"
    "    return \"0\" <= c and c <= \"9\"\n"
    "\n"
    "def is_alnum(c):\n"
    "    return is_alpha(c) or is_digit(c)\n"
    "\n"
    "def quote_string(s):\n"
    "    out : \"\"\n"
    "    i : 0\n"
    "    while i < len(s):\n"
    "        c : s[i]\n"
    "        if c = \"\\\\\":\n"
    "            out += \"\\\\\\\\\"\n"
    "        elif c = \"\\\"\":\n"
    "            out += \"\\\\\\\"\"\n"
    "        elif c = \"\\n\":\n"
    "            out += \"\\\\n\"\n"
    "        elif c = \"\\t\":\n"
    "            out += \"\\\\t\"\n"
    "        else:\n"
    "            out += c\n"
    "        i += 1\n"
    "    return \"\\\"\" + out + \"\\\"\"\n"
    "\n"
    "def num_clean(t):\n"
    "    out : \"\"\n"
    "    i : 0\n"
    "    while i < len(t):\n"
    "        c : t[i]\n"
    "        if c != \"_\":\n"
    "            out += c\n"
    "        i += 1\n"
    "    return out\n"
    "\n"
    "def lex_string(src, i, ln, col):\n"
    "    start : i\n"
    "    q : src[i]\n"
    "    i += 1\n"
    "    val : \"\"\n"
    "    while i < len(src):\n"
    "        c : src[i]\n"
    "        if c = q:\n"
    "            i += 1\n"
    "            return [tok(\"STRING\", src[start:i], {\"s\":val}, ln, col), i]\n"
    "        if c = \"\\n\":\n"
    "            raise str(ln) + \":\" + str(col) + \": unterminated string\"\n"
    "        if c = \"\\\\\":\n"
    "            if i + 1 >= len(src):\n"
    "                raise str(ln) + \":\" + str(col) + \": unterminated string\"\n"
    "            e : src[i + 1]\n"
    "            if e = \"n\":\n"
    "                val += \"\\n\"\n"
    "            elif e = \"t\":\n"
    "                val += \"\\t\"\n"
    "            elif e = \"r\":\n"
    "                val += \"\\r\"\n"
    "            elif e = \"\\\"\":\n"
    "                val += \"\\\"\"\n"
    "            elif e = \"'\":\n"
    "                val += \"'\"\n"
    "            elif e = \"\\\\\":\n"
    "                val += \"\\\\\"\n"
    "            else:\n"
    "                val += e\n"
    "            i += 2\n"
    "        else:\n"
    "            val += c\n"
    "            i += 1\n"
    "    raise str(ln) + \":\" + str(col) + \": unterminated string\"\n"
    "\n"
    "def lex(source):\n"
    "    n : len(source)\n"
    "    ts : []\n"
    "    comments : {\"0\":\"\"}\n"
    "    inline : {\"0\":\"\"}\n"
    "    i : 0\n"
    "    ln : 1\n"
    "    line_start : 0\n"
    "    line_has_code : False\n"
    "    while i < n:\n"
    "        c : source[i]\n"
    "        if c = \"\\n\":\n"
    "            ln += 1\n"
    "            i += 1\n"
    "            line_start : i\n"
    "            line_has_code : False\n"
    "            continue\n"
    "        if c = \" \" or c = \"\\t\" or c = \"\\r\":\n"
    "            i += 1\n"
    "            continue\n"
    "        col : i - line_start + 1\n"
    "        if c = \"#\":\n"
    "            j : i + 1\n"
    "            while j < n and source[j] != \"\\n\":\n"
    "                j += 1\n"
    "            line : source[i:j]\n"
    "            if starts(line, \"#include\"):\n"
    "                i : j\n"
    "                continue\n"
    "            raise str(ln) + \":\" + str(col) + \": unsupported preprocessor directive\"\n"
    "        if c = \"/\" and i + 1 < n and source[i + 1] = \"/\":\n"
    "            j : i + 2\n"
    "            while j < n and source[j] != \"\\n\":\n"
    "                j += 1\n"
    "            text : \"#\" + source[i + 2:j]\n"
    "            if line_has_code:\n"
    "                inline[str(ln)] : text\n"
    "            else:\n"
    "                comments[str(ln)] : text\n"
    "            i : j\n"
    "            continue\n"
    "        if c = \"/\" and i + 1 < n and source[i + 1] = \"*\":\n"
    "            start_ln : ln\n"
    "            j : i + 2\n"
    "            while j + 1 < n and not (source[j] = \"*\" and source[j + 1] = \"/\"):\n"
    "                if source[j] = \"\\n\":\n"
    "                    ln += 1\n"
    "                    line_start : j + 1\n"
    "                j += 1\n"
    "            if not (j + 1 < n and source[j] = \"*\" and source[j + 1] = \"/\"):\n"
    "                raise str(start_ln) + \":\" + str(col) + \": unterminated block comment\"\n"
    "            i : j + 2\n"
    "            continue\n"
    "        line_has_code : True\n"
    "        if is_alpha(c):\n"
    "            j : i + 1\n"
    "            while j < n and is_alnum(source[j]):\n"
    "                j += 1\n"
    "            text : source[i:j]\n"
    "            ts.append(tok(\"NAME\", text, text, ln, col))\n"
    "            i : j\n"
    "            continue\n"
    "        if is_digit(c) or (c = \".\" and i + 1 < n and is_digit(source[i + 1])):\n"
    "            j : i + 1\n"
    "            while j < n:\n"
    "                cj : source[j]\n"
    "                if is_alnum(cj) or cj = \"_\":\n"
    "                    j += 1\n"
    "                elif cj = \".\" and j + 1 < n and is_digit(source[j + 1]):\n"
    "                    j += 1\n"
    "                else:\n"
    "                    break\n"
    "            text : num_clean(source[i:j])\n"
    "            ts.append(tok(\"NUMBER\", text, text, ln, col))\n"
    "            i : j\n"
    "            continue\n"
    "        if c = \"\\\"\" or c = \"'\":\n"
    "            z : lex_string(source, i, ln, col)\n"
    "            ts.append(z[0])\n"
    "            i : z[1]\n"
    "            continue\n"
    "        op : c\n"
    "        if i + 1 < n:\n"
    "            two : source[i:i + 2]\n"
    "            if two in two_ops:\n"
    "                op : two\n"
    "        ts.append(tok(\"OP\", op, op, ln, col))\n"
    "        i += len(op)\n"
    "    ts.append(tok(\"END\", \"\", None, ln, i - line_start + 1))\n"
    "    return {\"tokens\":ts, \"comments\":comments, \"inline\":inline}\n"
    "\n"
    "def peek(p):\n"
    "    return p[\"tokens\"][p[\"pos\"]]\n"
    "\n"
    "def peekn(p, k):\n"
    "    j : p[\"pos\"] + k\n"
    "    if j >= len(p[\"tokens\"]):\n"
    "        j : len(p[\"tokens\"]) - 1\n"
    "    return p[\"tokens\"][j]\n"
    "\n"
    "def take(p):\n"
    "    x : peek(p)\n"
    "    p[\"pos\"] += 1\n"
    "    return x\n"
    "\n"
    "def at(p, text):\n"
    "    return peek(p)[\"text\"] = text\n"
    "\n"
    "def kind(p, k):\n"
    "    return peek(p)[\"kind\"] = k\n"
    "\n"
    "def fail(p, msg, x):\n"
    "    raise p[\"filename\"] + \":\" + str(x[\"line\"]) + \":\" + str(x[\"col\"]) + \": \" + msg\n"
    "\n"
    "def need(p, text):\n"
    "    x : peek(p)\n"
    "    if x[\"text\"] != text:\n"
    "        fail(p, \"expected '\" + text + \"'\", x)\n"
    "    return take(p)\n"
    "\n"
    "def need_kind(p, k):\n"
    "    x : peek(p)\n"
    "    if x[\"kind\"] != k:\n"
    "        fail(p, \"expected \" + k, x)\n"
    "    return take(p)\n"
    "\n"
    "def ident(p, x):\n"
    "    name : x[\"text\"]\n"
    "    if name in shakti_reserved or starts(name, \"__c_\"):\n"
    "        name : \"__c_\" + name\n"
    "    x[\"text\"] : name\n"
    "    return name\n"
    "\n"
    "def reject_pointer_type(p):\n"
    "    if at(p, \"*\"):\n"
    "        fail(p, \"pointer types are unsupported\", peek(p))\n"
    "\n"
    "def skip_type(p):\n"
    "    if not kind(p, \"NAME\"):\n"
    "        return False\n"
    "    saw : False\n"
    "    while kind(p, \"NAME\"):\n"
    "        t : peek(p)[\"text\"]\n"
    "        if is_type_mod(t):\n"
    "            take(p)\n"
    "        elif is_type_kw(t) or t = \"size_t\":\n"
    "            take(p)\n"
    "            saw : True\n"
    "        elif is_kw(t):\n"
    "            return False\n"
    "        else:\n"
    "            break\n"
    "    if not saw:\n"
    "        return False\n"
    "    return True\n"
    "\n"
    "def skip_main_param_type(p):\n"
    "    if not skip_type(p):\n"
    "        return False\n"
    "    while at(p, \"*\"):\n"
    "        take(p)\n"
    "    while at(p, \"[\"):\n"
    "        take(p)\n"
    "        if not at(p, \"]\"):\n"
    "            fail(p, \"sized array parameters are unsupported\", peek(p))\n"
    "        take(p)\n"
    "    return True\n"
    "\n"
    "def parse_main_params(p):\n"
    "    need(p, \"(\")\n"
    "    if at(p, \"void\"):\n"
    "        take(p)\n"
    "        need(p, \")\")\n"
    "        return []\n"
    "    if at(p, \")\"):\n"
    "        take(p)\n"
    "        return []\n"
    "    args : []\n"
    "    while not at(p, \")\"):\n"
    "        if not skip_main_param_type(p):\n"
    "            fail(p, \"expected main parameter type\", peek(p))\n"
    "        if kind(p, \"NAME\"):\n"
    "            a : take(p)\n"
    "            ident(p, a)\n"
    "            args.append(a[\"text\"])\n"
    "        if not at(p, \")\"):\n"
    "            need(p, \",\")\n"
    "    need(p, \")\")\n"
    "    return args\n"
    "\n"
    "def parse(source, filename):\n"
    "    lx : lex(source)\n"
    "    p : {\"tokens\":lx[\"tokens\"], \"pos\":0, \"filename\":filename, \"aliases\":{},\n"
    "         \"comments\":lx[\"comments\"], \"inline\":lx[\"inline\"], \"has_main\":False,\n"
    "         \"main_arity\":0}\n"
    "    body : []\n"
    "    while not kind(p, \"END\"):\n"
    "        body.append(parse_stmt(p))\n"
    "    if p[\"has_main\"]:\n"
    "        x : peek(p)\n"
    "        call : node(\"Expr\", x)\n"
    "        c : node(\"Call\", x)\n"
    "        fn : node(\"Name\", x)\n"
    "        fn[\"value\"] : \"main\"\n"
    "        c[\"func\"] : fn\n"
    "        c[\"args\"] : []\n"
    "        c[\"kwargs\"] : []\n"
    "        if p[\"main_arity\"] >= 1:\n"
    "            sl : node(\"Subscript\", x)\n"
    "            av : node(\"Name\", x)\n"
    "            av[\"value\"] : \"argv\"\n"
    "            sl[\"value\"] : av\n"
    "            slice : node(\"Slice\", x)\n"
    "            one : node(\"Const\", x)\n"
    "            one[\"value\"] : \"1\"\n"
    "            one[\"kind\"] : \"number\"\n"
    "            slice[\"lower\"] : one\n"
    "            slice[\"upper\"] : None\n"
    "            slice[\"step\"] : None\n"
    "            sl[\"slice\"] : slice\n"
    "            if p[\"main_arity\"] >= 2:\n"
    "                ln : node(\"Call\", x)\n"
    "                lf : node(\"Name\", x)\n"
    "                lf[\"value\"] : \"len\"\n"
    "                ln[\"func\"] : lf\n"
    "                ln[\"args\"] : [sl]\n"
    "                ln[\"kwargs\"] : []\n"
    "                c[\"args\"].append(ln)\n"
    "                # second argv[1:] needs a fresh Subscript node\n"
    "                sl2 : node(\"Subscript\", x)\n"
    "                av2 : node(\"Name\", x)\n"
    "                av2[\"value\"] : \"argv\"\n"
    "                sl2[\"value\"] : av2\n"
    "                slice2 : node(\"Slice\", x)\n"
    "                one2 : node(\"Const\", x)\n"
    "                one2[\"value\"] : \"1\"\n"
    "                one2[\"kind\"] : \"number\"\n"
    "                slice2[\"lower\"] : one2\n"
    "                slice2[\"upper\"] : None\n"
    "                slice2[\"step\"] : None\n"
    "                sl2[\"slice\"] : slice2\n"
    "                c[\"args\"].append(sl2)\n"
    "            else:\n"
    "                c[\"args\"].append(sl)\n"
    "        call[\"value\"] : c\n"
    "        body.append(call)\n"
    "    return {\"t\":\"Module\", \"body\":body, \"comments\":p[\"comments\"], \"inline\":p[\"inline\"],\n"
    "            \"aliases\":p[\"aliases\"], \"filename\":filename, \"has_main\":p[\"has_main\"]}\n"
    "\n"
    "def parse_stmt(p):\n"
    "    x : peek(p)\n"
    "    if at(p, \"struct\") or at(p, \"union\") or at(p, \"enum\") or at(p, \"typedef\"):\n"
    "        fail(p, x[\"text\"] + \" declarations are unsupported\", x)\n"
    "    if at(p, \"try\") or at(p, \"switch\") or at(p, \"do\") or at(p, \"goto\"):\n"
    "        fail(p, x[\"text\"] + \" statements are unsupported\", x)\n"
    "    if at(p, \"if\"):\n"
    "        return parse_if(p)\n"
    "    if at(p, \"while\"):\n"
    "        return parse_while(p)\n"
    "    if at(p, \"for\"):\n"
    "        return parse_for(p)\n"
    "    if at(p, \"return\"):\n"
    "        return parse_return(p)\n"
    "    if at(p, \"break\") or at(p, \"continue\"):\n"
    "        take(p)\n"
    "        z : node(x[\"text\"], x)\n"
    "        need(p, \";\")\n"
    "        return z\n"
    "    if at(p, \"{\"):\n"
    "        fail(p, \"unexpected block\", x)\n"
    "    fn : try_parse_func(p)\n"
    "    if fn != None:\n"
    "        return fn\n"
    "    d : try_parse_decl(p)\n"
    "    if d != None:\n"
    "        return d\n"
    "    return parse_expr_stmt(p)\n"
    "\n"
    "def try_parse_func(p):\n"
    "    save : p[\"pos\"]\n"
    "    ok : skip_type(p)\n"
    "    if not ok:\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    reject_pointer_type(p)\n"
    "    if not kind(p, \"NAME\") or is_kw(peek(p)[\"text\"]):\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    name_tok : peek(p)\n"
    "    if peekn(p, 1)[\"text\"] != \"(\":\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    x : name_tok\n"
    "    take(p)\n"
    "    ident(p, name_tok)\n"
    "    z : node(\"FunctionDef\", x)\n"
    "    z[\"name\"] : name_tok[\"text\"]\n"
    "    z[\"decorators\"] : []\n"
    "    z[\"defaults\"] : []\n"
    "    if name_tok[\"text\"] = \"main\":\n"
    "        p[\"has_main\"] : True\n"
    "        args : parse_main_params(p)\n"
    "        z[\"args\"] : args\n"
    "        defaults : []\n"
    "        for a in args:\n"
    "            defaults.append(None)\n"
    "        z[\"defaults\"] : defaults\n"
    "        p[\"main_arity\"] : len(args)\n"
    "    else:\n"
    "        need(p, \"(\")\n"
    "        args : []\n"
    "        defaults : []\n"
    "        if not at(p, \")\"):\n"
    "            while True:\n"
    "                if not skip_type(p):\n"
    "                    fail(p, \"expected parameter type\", peek(p))\n"
    "                reject_pointer_type(p)\n"
    "                a : need_kind(p, \"NAME\")\n"
    "                while at(p, \"[\"):\n"
    "                    take(p)\n"
    "                    if not at(p, \"]\"):\n"
    "                        fail(p, \"sized array parameters are unsupported\", peek(p))\n"
    "                    take(p)\n"
    "                ident(p, a)\n"
    "                args.append(a[\"text\"])\n"
    "                defaults.append(None)\n"
    "                if not at(p, \",\"):\n"
    "                    break\n"
    "                take(p)\n"
    "        need(p, \")\")\n"
    "        z[\"args\"] : args\n"
    "        z[\"defaults\"] : defaults\n"
    "    z[\"body\"] : parse_block(p)\n"
    "    return z\n"
    "\n"
    "def try_parse_decl(p):\n"
    "    save : p[\"pos\"]\n"
    "    ok : skip_type(p)\n"
    "    if not ok:\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    reject_pointer_type(p)\n"
    "    if not kind(p, \"NAME\") or is_kw(peek(p)[\"text\"]):\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    name_tok : peek(p)\n"
    "    j : 1\n"
    "    while peekn(p, j)[\"text\"] = \"[\":\n"
    "        if peekn(p, j + 1)[\"text\"] = \"]\":\n"
    "            j += 2\n"
    "        elif peekn(p, j + 1)[\"kind\"] = \"NUMBER\" and peekn(p, j + 2)[\"text\"] = \"]\":\n"
    "            j += 3\n"
    "        else:\n"
    "            p[\"pos\"] : save\n"
    "            return None\n"
    "    if peekn(p, j)[\"text\"] != \"=\":\n"
    "        p[\"pos\"] : save\n"
    "        return None\n"
    "    x : name_tok\n"
    "    take(p)\n"
    "    while at(p, \"[\"):\n"
    "        take(p)\n"
    "        if not at(p, \"]\"):\n"
    "            if kind(p, \"NUMBER\"):\n"
    "                take(p)\n"
    "            else:\n"
    "                fail(p, \"sized array declarations require a numeric bound or []\", peek(p))\n"
    "        need(p, \"]\")\n"
    "    ident(p, name_tok)\n"
    "    need(p, \"=\")\n"
    "    value : parse_expr(p)\n"
    "    need(p, \";\")\n"
    "    z : node(\"Assign\", x)\n"
    "    tgt : node(\"Name\", x)\n"
    "    tgt[\"value\"] : name_tok[\"text\"]\n"
    "    z[\"target\"] : tgt\n"
    "    z[\"value\"] : value\n"
    "    return z\n"
    "\n"
    "def parse_block(p):\n"
    "    lb : need(p, \"{\")\n"
    "    xs : []\n"
    "    while not at(p, \"}\") and not kind(p, \"END\"):\n"
    "        xs.append(parse_stmt(p))\n"
    "    need(p, \"}\")\n"
    "    if len(xs) = 0:\n"
    "        px : node(\"pass\", lb)\n"
    "        return [px]\n"
    "    return xs\n"
    "\n"
    "def parse_block_or_stmt(p):\n"
    "    if at(p, \"{\"):\n"
    "        return parse_block(p)\n"
    "    return [parse_stmt(p)]\n"
    "\n"
    "def parse_return(p):\n"
    "    x : take(p)\n"
    "    z : node(\"Return\", x)\n"
    "    z[\"value\"] : None\n"
    "    if not at(p, \";\"):\n"
    "        z[\"value\"] : parse_expr(p)\n"
    "    need(p, \";\")\n"
    "    return z\n"
    "\n"
    "def parse_if(p):\n"
    "    x : take(p)\n"
    "    need(p, \"(\")\n"
    "    test : parse_expr(p)\n"
    "    need(p, \")\")\n"
    "    z : node(\"If\", x)\n"
    "    z[\"test\"] : test\n"
    "    z[\"body\"] : parse_block_or_stmt(p)\n"
    "    z[\"elifs\"] : []\n"
    "    z[\"orelse\"] : []\n"
    "    while at(p, \"else\") and peekn(p, 1)[\"text\"] = \"if\":\n"
    "        e : take(p)\n"
    "        take(p)\n"
    "        need(p, \"(\")\n"
    "        et : parse_expr(p)\n"
    "        need(p, \")\")\n"
    "        eb : parse_block_or_stmt(p)\n"
    "        z[\"elifs\"].append({\"test\":et, \"body\":eb, \"line\":e[\"line\"], \"col\":e[\"col\"]})\n"
    "    if at(p, \"else\"):\n"
    "        take(p)\n"
    "        z[\"orelse\"] : parse_block_or_stmt(p)\n"
    "    return z\n"
    "\n"
    "def parse_while(p):\n"
    "    x : take(p)\n"
    "    need(p, \"(\")\n"
    "    t : parse_expr(p)\n"
    "    need(p, \")\")\n"
    "    z : node(\"While\", x)\n"
    "    z[\"test\"] : t\n"
    "    z[\"body\"] : parse_block_or_stmt(p)\n"
    "    return z\n"
    "\n"
    "def parse_for(p):\n"
    "    x : take(p)\n"
    "    need(p, \"(\")\n"
    "    init : None\n"
    "    if not at(p, \";\"):\n"
    "        init : parse_for_clause(p)\n"
    "    need(p, \";\")\n"
    "    cond : None\n"
    "    if not at(p, \";\"):\n"
    "        cond : parse_expr(p)\n"
    "    need(p, \";\")\n"
    "    upd : None\n"
    "    if not at(p, \")\"):\n"
    "        upd : parse_assign_no_semi(p)\n"
    "    need(p, \")\")\n"
    "    body : parse_block_or_stmt(p)\n"
    "    w : node(\"While\", x)\n"
    "    if cond = None:\n"
    "        tc : node(\"Const\", x)\n"
    "        tc[\"value\"] : \"True\"\n"
    "        tc[\"kind\"] : \"number\"\n"
    "        w[\"test\"] : tc\n"
    "    else:\n"
    "        w[\"test\"] : cond\n"
    "    b2 : []\n"
    "    for s in body:\n"
    "        b2.append(s)\n"
    "    if upd != None:\n"
    "        b2.append(upd)\n"
    "    w[\"body\"] : b2\n"
    "    seq : node(\"Seq\", x)\n"
    "    stmts : []\n"
    "    if init != None:\n"
    "        stmts.append(init)\n"
    "    stmts.append(w)\n"
    "    seq[\"body\"] : stmts\n"
    "    return seq\n"
    "\n"
    "def parse_for_clause(p):\n"
    "    x : peek(p)\n"
    "    save : p[\"pos\"]\n"
    "    if skip_type(p):\n"
    "        reject_pointer_type(p)\n"
    "        if kind(p, \"NAME\") and not is_kw(peek(p)[\"text\"]) and peekn(p, 1)[\"text\"] = \"=\":\n"
    "            nt : take(p)\n"
    "            ident(p, nt)\n"
    "            need(p, \"=\")\n"
    "            v : parse_expr(p)\n"
    "            z : node(\"Assign\", x)\n"
    "            tg : node(\"Name\", x)\n"
    "            tg[\"value\"] : nt[\"text\"]\n"
    "            z[\"target\"] : tg\n"
    "            z[\"value\"] : v\n"
    "            return z\n"
    "    p[\"pos\"] : save\n"
    "    return parse_assign_no_semi(p)\n"
    "\n"
    "def parse_assign_no_semi(p):\n"
    "    x : peek(p)\n"
    "    left : parse_expr(p)\n"
    "    tt : peek(p)[\"text\"]\n"
    "    if tt = \"=\":\n"
    "        take(p)\n"
    "        val : parse_expr(p)\n"
    "        z : node(\"Assign\", x)\n"
    "        z[\"target\"] : left\n"
    "        z[\"value\"] : val\n"
    "        validate_target(p, left)\n"
    "        return z\n"
    "    if tt in [\"+=\", \"-=\", \"*=\", \"/=\"]:\n"
    "        op : take(p)[\"text\"]\n"
    "        z : node(\"AugAssign\", x)\n"
    "        z[\"target\"] : left\n"
    "        validate_target(p, left)\n"
    "        z[\"op\"] : op\n"
    "        z[\"value\"] : parse_expr(p)\n"
    "        return z\n"
    "    if tt = \"++\" or tt = \"--\":\n"
    "        take(p)\n"
    "        z : node(\"AugAssign\", x)\n"
    "        z[\"target\"] : left\n"
    "        validate_target(p, left)\n"
    "        z[\"op\"] : \"+=\" if tt = \"++\" else \"-=\"\n"
    "        one : node(\"Const\", x)\n"
    "        one[\"value\"] : \"1\"\n"
    "        one[\"kind\"] : \"number\"\n"
    "        z[\"value\"] : one\n"
    "        return z\n"
    "    z : node(\"Expr\", x)\n"
    "    z[\"value\"] : left\n"
    "    return z\n"
    "\n"
    "def parse_expr_stmt(p):\n"
    "    z : parse_assign_no_semi(p)\n"
    "    need(p, \";\")\n"
    "    return z\n"
    "\n"
    "def validate_target(p, x):\n"
    "    if x[\"t\"] = \"Name\" or x[\"t\"] = \"Attr\" or x[\"t\"] = \"Subscript\":\n"
    "        return\n"
    "    fail(p, \"unsupported assignment target\", x)\n"
    "\n"
    "def parse_expr(p):\n"
    "    return parse_ternary(p)\n"
    "\n"
    "def parse_ternary(p):\n"
    "    c : parse_or(p)\n"
    "    if at(p, \"?\"):\n"
    "        take(p)\n"
    "        a : parse_expr(p)\n"
    "        need(p, \":\")\n"
    "        b : parse_expr(p)\n"
    "        z : node(\"IfExp\", c)\n"
    "        z[\"body\"] : a\n"
    "        z[\"test\"] : c\n"
    "        z[\"orelse\"] : b\n"
    "        return z\n"
    "    return c\n"
    "\n"
    "def parse_or(p):\n"
    "    xs : [parse_and(p)]\n"
    "    x : xs[0]\n"
    "    while at(p, \"||\"):\n"
    "        take(p)\n"
    "        xs.append(parse_and(p))\n"
    "    if len(xs) = 1:\n"
    "        return x\n"
    "    z : node(\"BoolOp\", x)\n"
    "    z[\"op\"] : \"or\"\n"
    "    z[\"values\"] : xs\n"
    "    return z\n"
    "\n"
    "def parse_and(p):\n"
    "    xs : [parse_bitand(p)]\n"
    "    x : xs[0]\n"
    "    while at(p, \"&&\"):\n"
    "        take(p)\n"
    "        xs.append(parse_bitand(p))\n"
    "    if len(xs) = 1:\n"
    "        return x\n"
    "    z : node(\"BoolOp\", x)\n"
    "    z[\"op\"] : \"and\"\n"
    "    z[\"values\"] : xs\n"
    "    return z\n"
    "\n"
    "def parse_bitand(p):\n"
    "    x : peek(p)\n"
    "    if at(p, \"&\") or at(p, \"|\") or at(p, \"^\") or at(p, \"~\"):\n"
    "        fail(p, \"bitwise operators are unsupported\", peek(p))\n"
    "    return parse_compare(p)\n"
    "\n"
    "def parse_compare(p):\n"
    "    left : parse_shift(p)\n"
    "    if peek(p)[\"text\"] in [\"==\", \"!=\", \"<\", \"<=\", \">\", \">=\"]:\n"
    "        op : take(p)[\"text\"]\n"
    "        right : parse_shift(p)\n"
    "        z : node(\"Compare\", left)\n"
    "        z[\"left\"] : left\n"
    "        z[\"op\"] : op\n"
    "        z[\"right\"] : right\n"
    "        return z\n"
    "    return left\n"
    "\n"
    "def parse_shift(p):\n"
    "    x : peek(p)\n"
    "    if at(p, \"<<\") or at(p, \">>\"):\n"
    "        fail(p, \"bitwise shift operators are unsupported\", peek(p))\n"
    "    return parse_add(p)\n"
    "\n"
    "def parse_add(p):\n"
    "    z : parse_mul(p)\n"
    "    while peek(p)[\"text\"] = \"+\" or peek(p)[\"text\"] = \"-\":\n"
    "        op : take(p)[\"text\"]\n"
    "        q : node(\"BinOp\", z)\n"
    "        q[\"left\"] : z\n"
    "        q[\"op\"] : op\n"
    "        q[\"right\"] : parse_mul(p)\n"
    "        z : q\n"
    "    return z\n"
    "\n"
    "def parse_mul(p):\n"
    "    z : parse_unary(p)\n"
    "    while peek(p)[\"text\"] in [\"*\", \"/\", \"%\"]:\n"
    "        op : take(p)[\"text\"]\n"
    "        q : node(\"BinOp\", z)\n"
    "        q[\"left\"] : z\n"
    "        q[\"op\"] : op\n"
    "        q[\"right\"] : parse_unary(p)\n"
    "        z : q\n"
    "    return z\n"
    "\n"
    "def parse_unary(p):\n"
    "    tt : peek(p)[\"text\"]\n"
    "    if tt = \"!\":\n"
    "        x : take(p)\n"
    "        z : node(\"Unary\", x)\n"
    "        z[\"op\"] : \"not\"\n"
    "        z[\"value\"] : parse_unary(p)\n"
    "        return z\n"
    "    if tt = \"-\":\n"
    "        x : take(p)\n"
    "        z : node(\"Unary\", x)\n"
    "        z[\"op\"] : \"-\"\n"
    "        z[\"value\"] : parse_unary(p)\n"
    "        return z\n"
    "    if tt = \"+\":\n"
    "        fail(p, \"unary plus is unsupported\", peek(p))\n"
    "    if tt = \"++\" or tt = \"--\":\n"
    "        fail(p, \"prefix increment is unsupported\", peek(p))\n"
    "    if tt = \"&\":\n"
    "        fail(p, \"address-of is unsupported\", peek(p))\n"
    "    if tt = \"*\":\n"
    "        fail(p, \"pointer dereference is unsupported\", peek(p))\n"
    "    if tt = \"~\":\n"
    "        fail(p, \"bitwise operators are unsupported\", peek(p))\n"
    "    return parse_postfix(p)\n"
    "\n"
    "def parse_postfix(p):\n"
    "    z : parse_atom(p)\n"
    "    while True:\n"
    "        if at(p, \".\"):\n"
    "            x : take(p)\n"
    "            a : need_kind(p, \"NAME\")\n"
    "            q : node(\"Attr\", x)\n"
    "            q[\"value\"] : z\n"
    "            q[\"attr\"] : a[\"text\"]\n"
    "            z : q\n"
    "        elif at(p, \"->\"):\n"
    "            fail(p, \"pointer member access is unsupported\", peek(p))\n"
    "        elif at(p, \"(\"):\n"
    "            x : take(p)\n"
    "            q : node(\"Call\", x)\n"
    "            q[\"func\"] : z\n"
    "            q[\"args\"] : []\n"
    "            q[\"kwargs\"] : []\n"
    "            if not at(p, \")\"):\n"
    "                while True:\n"
    "                    q[\"args\"].append(parse_expr(p))\n"
    "                    if not at(p, \",\"):\n"
    "                        break\n"
    "                    take(p)\n"
    "            need(p, \")\")\n"
    "            z : q\n"
    "        elif at(p, \"[\"):\n"
    "            x : take(p)\n"
    "            q : node(\"Subscript\", x)\n"
    "            q[\"value\"] : z\n"
    "            q[\"slice\"] : parse_index(p)\n"
    "            need(p, \"]\")\n"
    "            z : q\n"
    "        else:\n"
    "            break\n"
    "    return z\n"
    "\n"
    "def parse_index(p):\n"
    "    x : peek(p)\n"
    "    lower : None\n"
    "    if not at(p, \"]\"):\n"
    "        lower : parse_expr(p)\n"
    "    return lower\n"
    "\n"
    "def parse_array_init(p, x):\n"
    "    need(p, \"{\")\n"
    "    z : node(\"List\", x)\n"
    "    z[\"elts\"] : []\n"
    "    if not at(p, \"}\"):\n"
    "        while True:\n"
    "            z[\"elts\"].append(parse_expr(p))\n"
    "            if not at(p, \",\"):\n"
    "                break\n"
    "            take(p)\n"
    "            if at(p, \"}\"):\n"
    "                break\n"
    "    need(p, \"}\")\n"
    "    return z\n"
    "\n"
    "def parse_atom(p):\n"
    "    x : peek(p)\n"
    "    if kind(p, \"NUMBER\"):\n"
    "        take(p)\n"
    "        z : node(\"Const\", x)\n"
    "        z[\"value\"] : x[\"text\"]\n"
    "        z[\"kind\"] : \"number\"\n"
    "        return z\n"
    "    if kind(p, \"STRING\"):\n"
    "        take(p)\n"
    "        z : node(\"Const\", x)\n"
    "        z[\"value\"] : x[\"val\"][\"s\"]\n"
    "        z[\"kind\"] : \"string\"\n"
    "        return z\n"
    "    if at(p, \"true\") or at(p, \"false\") or at(p, \"NULL\"):\n"
    "        take(p)\n"
    "        z : node(\"Const\", x)\n"
    "        z[\"value\"] : \"True\" if x[\"text\"] = \"true\" else (\"False\" if x[\"text\"] = \"false\" else \"None\")\n"
    "        z[\"kind\"] : \"number\"\n"
    "        return z\n"
    "    if kind(p, \"NAME\"):\n"
    "        take(p)\n"
    "        if is_kw(x[\"text\"]):\n"
    "            fail(p, \"unexpected keyword '\" + x[\"text\"] + \"'\", x)\n"
    "        if x[\"text\"] in c_forbidden_names:\n"
    "            fail(p, x[\"text\"] + \" is unsupported\", x)\n"
    "        z : node(\"Name\", x)\n"
    "        z[\"value\"] : ident(p, x)\n"
    "        x[\"text\"] : z[\"value\"]\n"
    "        return z\n"
    "    if at(p, \"(\"):\n"
    "        take(p)\n"
    "        z : parse_expr(p)\n"
    "        need(p, \")\")\n"
    "        return z\n"
    "    if at(p, \"{\"):\n"
    "        return parse_array_init(p, x)\n"
    "    fail(p, \"unsupported expression\", x)\n"
    "\n"
    "def pad(n):\n"
    "    return \"    \" * n\n"
    "\n"
    "def render(ast, state):\n"
    "    state[\"comments\"] : ast[\"comments\"]\n"
    "    state[\"inline\"] : ast[\"inline\"]\n"
    "    state[\"last_comment\"] : 0\n"
    "    state[\"filename\"] : ast[\"filename\"]\n"
    "    lines : render_body(ast[\"body\"], state, 0, True)\n"
    "    for k in state[\"comments\"].keys():\n"
    "        kn : int(k)\n"
    "        if kn > state[\"last_comment\"]:\n"
    "            lines.append(state[\"comments\"][k])\n"
    "    text : \"\"\n"
    "    for line in lines:\n"
    "        if line != \"\":\n"
    "            text += line + \"\\n\"\n"
    "    return text\n"
    "\n"
    "def before_comments(st, line, indent):\n"
    "    out : []\n"
    "    for k in st[\"comments\"].keys():\n"
    "        kn : int(k)\n"
    "        if kn > st[\"last_comment\"] and kn < line:\n"
    "            out.append(pad(indent) + st[\"comments\"][k])\n"
    "            st[\"last_comment\"] : kn\n"
    "    return out\n"
    "\n"
    "def render_body(body, st, indent, doc_ok):\n"
    "    out : []\n"
    "    i : 0\n"
    "    while i < len(body):\n"
    "        s : body[i]\n"
    "        cs : before_comments(st, s[\"line\"], indent)\n"
    "        for c in cs:\n"
    "            out.append(c)\n"
    "        rs : render_stmt(s, st, indent)\n"
    "        key : str(s[\"line\"])\n"
    "        if key in st[\"inline\"] and len(rs) > 0:\n"
    "            rs[0] : rs[0] + \"  \" + st[\"inline\"][key]\n"
    "        for q in rs:\n"
    "            if q != \"\":\n"
    "                out.append(q)\n"
    "        i += 1\n"
    "    return out\n"
    "\n"
    "def render_stmt(s, st, ind):\n"
    "    p : pad(ind)\n"
    "    t : s[\"t\"]\n"
    "    if t = \"Seq\":\n"
    "        out : []\n"
    "        for c in s[\"body\"]:\n"
    "            for q in render_stmt(c, st, ind):\n"
    "                out.append(q)\n"
    "        return out\n"
    "    if t = \"Assign\":\n"
    "        return [p + target_text(s[\"target\"], st) + \" : \" + expr_text(s[\"value\"], st)]\n"
    "    if t = \"AugAssign\":\n"
    "        return [p + target_text(s[\"target\"], st) + \" \" + s[\"op\"] + \" \" + expr_text(s[\"value\"], st)]\n"
    "    if t = \"Return\":\n"
    "        return [p + (\"return\" if s[\"value\"] = None else \"return \" + expr_text(s[\"value\"], st))]\n"
    "    if t = \"break\" or t = \"continue\" or t = \"pass\":\n"
    "        return [p + t]\n"
    "    if t = \"Expr\":\n"
    "        return [p + expr_text(s[\"value\"], st)]\n"
    "    if t = \"FunctionDef\":\n"
    "        out : []\n"
    "        for d in s[\"decorators\"]:\n"
    "            out.append(p + \"@\" + expr_text(d, st))\n"
    "        parts : []\n"
    "        i : 0\n"
    "        while i < len(s[\"args\"]):\n"
    "            q : s[\"args\"][i]\n"
    "            if s[\"defaults\"][i] != None:\n"
    "                q += \":\" + expr_text(s[\"defaults\"][i], st)\n"
    "            parts.append(q)\n"
    "            i += 1\n"
    "        out.append(p + \"def \" + s[\"name\"] + \"(\" + join_text(parts, \", \") + \"):\")\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, True):\n"
    "            out.append(q)\n"
    "        return out\n"
    "    if t = \"If\":\n"
    "        out : [p + \"if \" + expr_text(s[\"test\"], st) + \":\"]\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "            out.append(q)\n"
    "        for e in s[\"elifs\"]:\n"
    "            out.append(p + \"elif \" + expr_text(e[\"test\"], st) + \":\")\n"
    "            for q in render_body(e[\"body\"], st, ind + 1, False):\n"
    "                out.append(q)\n"
    "        if len(s[\"orelse\"]) > 0:\n"
    "            out.append(p + \"else:\")\n"
    "            for q in render_body(s[\"orelse\"], st, ind + 1, False):\n"
    "                out.append(q)\n"
    "        return out\n"
    "    if t = \"While\":\n"
    "        out : [p + \"while \" + expr_text(s[\"test\"], st) + \":\"]\n"
    "        for q in render_body(s[\"body\"], st, ind + 1, False):\n"
    "            out.append(q)\n"
    "        return out\n"
    "    return []\n"
    "\n"
    "def join_text(xs, sep):\n"
    "    out : \"\"\n"
    "    i : 0\n"
    "    while i < len(xs):\n"
    "        if i > 0:\n"
    "            out += sep\n"
    "        out += xs[i]\n"
    "        i += 1\n"
    "    return out\n"
    "\n"
    "def target_text(x, st):\n"
    "    if x[\"t\"] = \"Tuple\" or x[\"t\"] = \"List\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(target_text(e, st))\n"
    "        return join_text(parts, \", \")\n"
    "    return expr_text(x, st)\n"
    "\n"
    "def slice_text(x, st):\n"
    "    if x[\"t\"] = \"Slice\":\n"
    "        a : \"\" if x[\"lower\"] = None else expr_text(x[\"lower\"], st)\n"
    "        b : \"\" if x[\"upper\"] = None else expr_text(x[\"upper\"], st)\n"
    "        q : a + \":\" + b\n"
    "        if x[\"step\"] != None:\n"
    "            q += \":\" + expr_text(x[\"step\"], st)\n"
    "        return q\n"
    "    return expr_text(x, st)\n"
    "\n"
    "def expr_text(x, st):\n"
    "    t : x[\"t\"]\n"
    "    if t = \"Name\":\n"
    "        return x[\"value\"]\n"
    "    if t = \"Const\":\n"
    "        if x[\"kind\"] = \"string\":\n"
    "            return quote_string(x[\"value\"])\n"
    "        return x[\"value\"]\n"
    "    if t = \"List\":\n"
    "        parts : []\n"
    "        for e in x[\"elts\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return \"[\" + join_text(parts, \", \") + \"]\"\n"
    "    if t = \"Attr\":\n"
    "        return expr_text(x[\"value\"], st) + \".\" + x[\"attr\"]\n"
    "    if t = \"Subscript\":\n"
    "        return expr_text(x[\"value\"], st) + \"[\" + slice_text(x[\"slice\"], st) + \"]\"\n"
    "    if t = \"Unary\":\n"
    "        return \"(\" + (\"not \" if x[\"op\"] = \"not\" else \"-\") + expr_text(x[\"value\"], st) + \")\"\n"
    "    if t = \"BinOp\":\n"
    "        if x[\"op\"] = \"+\" and (is_stringy(x[\"left\"]) or is_stringy(x[\"right\"])):\n"
    "            return \"(\" + string_operand(x[\"left\"], st) + \" + \" + string_operand(x[\"right\"], st) + \")\"\n"
    "        return \"(\" + expr_text(x[\"left\"], st) + \" \" + x[\"op\"] + \" \" + expr_text(x[\"right\"], st) + \")\"\n"
    "    if t = \"BoolOp\":\n"
    "        parts : []\n"
    "        for e in x[\"values\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return \"(\" + join_text(parts, \" \" + x[\"op\"] + \" \") + \")\"\n"
    "    if t = \"Compare\":\n"
    "        op : \"=\" if x[\"op\"] = \"==\" else x[\"op\"]\n"
    "        return \"(\" + expr_text(x[\"left\"], st) + \" \" + op + \" \" + expr_text(x[\"right\"], st) + \")\"\n"
    "    if t = \"IfExp\":\n"
    "        return expr_text(x[\"body\"], st) + \" if \" + expr_text(x[\"test\"], st) + \" else \" + expr_text(x[\"orelse\"], st)\n"
    "    if t = \"Call\":\n"
    "        lowered : lower_call(x, st)\n"
    "        if lowered != None:\n"
    "            return lowered\n"
    "        parts : []\n"
    "        for e in x[\"args\"]:\n"
    "            parts.append(expr_text(e, st))\n"
    "        return expr_text(x[\"func\"], st) + \"(\" + join_text(parts, \", \") + \")\"\n"
    "    return \"\"\n"
    "\n"
    "def is_stringy(x):\n"
    "    if x[\"t\"] = \"Const\" and x[\"kind\"] = \"string\":\n"
    "        return True\n"
    "    if x[\"t\"] = \"BinOp\" and x[\"op\"] = \"+\" and (is_stringy(x[\"left\"]) or is_stringy(x[\"right\"])):\n"
    "        return True\n"
    "    return False\n"
    "\n"
    "def string_operand(x, st):\n"
    "    if is_stringy(x) and not (x[\"t\"] = \"BinOp\" and x[\"op\"] = \"+\"):\n"
    "        return expr_text(x, st)\n"
    "    if x[\"t\"] = \"BinOp\" and x[\"op\"] = \"+\" and (is_stringy(x[\"left\"]) or is_stringy(x[\"right\"])):\n"
    "        return expr_text(x, st)\n"
    "    return \"str(\" + expr_text(x, st) + \")\"\n"
    "\n"
    "def lower_call(x, st):\n"
    "    f : x[\"func\"]\n"
    "    if f[\"t\"] = \"Name\":\n"
    "        name : f[\"value\"]\n"
    "        if name = \"printf\" or name = \"puts\":\n"
    "            parts : []\n"
    "            for e in x[\"args\"]:\n"
    "                parts.append(expr_text(e, st))\n"
    "            return \"print(\" + join_text(parts, \", \") + \")\"\n"
    "    return None\n"
    "\n"
    "def transpile(source, filename):\n"
    "    ast : parse(source, filename)\n"
    "    return render(ast, {\"aliases\":ast[\"aliases\"]})\n"
    "\n"
    "def main():\n"
    "    if len(argv) < 2:\n"
    "        raise \"usage: c2s.ie input.c [-o out.ie]\"\n"
    "    inp : None\n"
    "    out : None\n"
    "    i : 1\n"
    "    while i < len(argv):\n"
    "        if argv[i] = \"-o\" or argv[i] = \"--output\":\n"
    "            if i + 1 >= len(argv):\n"
    "                raise \"missing output path\"\n"
    "            out : argv[i + 1]\n"
    "            i += 2\n"
    "        elif argv[i][0] = \"-\":\n"
    "            raise \"unknown option: \" + argv[i]\n"
    "        elif inp = None:\n"
    "            inp : argv[i]\n"
    "            i += 1\n"
    "        else:\n"
    "            raise \"unexpected argument: \" + argv[i]\n"
    "    if inp = None:\n"
    "        raise \"usage: c2s.ie input.c [-o out.ie]\"\n"
    "    result : transpile(read(inp), inp)\n"
    "    if out = None:\n"
    "        write(\"/dev/stdout\", result)\n"
    "    else:\n"
    "        write(out, result)\n"
    "\n"
    "# Run CLI only when this file is the entry script.\n"
    "if re_match(\"c2s\\\\.ie$\", argv[0]):\n"
    "    main()\n"
;
#endif /* SHAKTI_SHAKTI_C2S_SOURCE_H */
